### ISSUE TITLE
No scrollbars for string editor with many values

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#100]
Dialog is too big to fit all values, but no scrollbar is created anywhere. Might be related to fixed positioning of the popover dialog

![20160929_manyvalues](https://cloud.githubusercontent.com/assets/8982136/18957115/22334b38-865e-11e6-9b6d-45125513ab71.PNG)

**Comment by philippfromme** [comment]
Applies to any dropdown, might not be fully accessable somtimes.

<img width="960" alt="foo" src="https://user-images.githubusercontent.com/7633572/28958858-55401b7c-78f8-11e7-94c7-ae0445c132ed.png">

**Comment by nikku** [comment]
We work around this in `dmn-js@2.x` by scrolling to make all entries fit.
