### ISSUE TITLE
decision elements are part of drgElements collection

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#109]
This will be done in dmn-moddle and needs to be addressed in dmn-js.

**Comment by SebastianStamm** [comment]
It is no longer possible to access the decision tables. The index which table should be shown is determined by the list of decisions ([Source](https://github.com/bpmn-io/dmn-js/commit/022f93f616e2f8decd690ab3507935006e2e6e05#diff-cdbc22cb068224645f98c2ef0dc2da35R215)), but then evaluated against the complete list of drgElements, that contains elements like inputData and knowledgeSources ([Source](https://github.com/bpmn-io/dmn-js/commit/022f93f616e2f8decd690ab3507935006e2e6e05#diff-e34440d8336dd00be5471eef974e7a79R33))

That results in the table viewer not displaying the selected decision, but being empty instead, as is cannot display inputData.

**Comment by nikku** [comment]
Please add test cases that verify what was wrong (and is now working) regarding this commit: https://github.com/bpmn-io/dmn-moddle/commit/af5b32d85017d917e659f1b56d8958c8e03da7dc.

**Comment by nikku** [comment]
WIthout test cases we cannot reliably tell whether the stuff you did breaks in the future or not.
