### ISSUE TITLE
I can append an element with the context pad

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#114]

**Comment by SebastianStamm** [comment]
Travis fails with "Error: Cannot find module 'diagram-js-direct-editing' from '/home/travis/build/bpmn-io/dmn-js/lib/features/context-pad'" [LINK](https://travis-ci.org/bpmn-io/dmn-js/builds/171374150)

I get the same error when trying to build.

**Comment by SebastianStamm** [comment]
The possibility to append a decision from an existing decision is missing. Rest looks fine :)
