### ISSUE TITLE
I can have multiple decisions being shown with tabs

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#115]
Provide the necessary infrastructure so the applications can have a tab system for multiple decisions

**Comment by SebastianStamm** [comment]
Currently, we provide an API to retrieve all decisions in the definitions: https://github.com/bpmn-io/dmn-js/blob/master/lib/table/Viewer.js#L185-L187 as well as an API to set the displayed decision table: https://github.com/bpmn-io/dmn-js/blob/master/lib/table/Viewer.js#L189-L216

What other infrastructure would be necessary?

**Comment by nikku** [comment]
We got that covered.

![image](https://user-images.githubusercontent.com/58601/37802675-c02931ba-2e2b-11e8-96fd-a8e881956945.png)
