### ISSUE TITLE
Add migration service so that you can check if we can parse the diagram and migrate it

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#119]
In this case we're not making sure the diagram is migrated, just providing infrastructure that the applications can either use or ignore. This would allows us not to have the same code implemented in several applications.

Also for the DI if the user loads a diagram without DI.

When switching to DRD it would add the DI.

**Comment by SebastianStamm** [comment]
Can this be closed now that we automatically fix the old, invalid namespace on import (#156)?
