### ISSUE TITLE
dmn-js logo font code is hardcoded in less file

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#12]
It is currently not possible to create combined DMN+... fonts because of the fact that the dmn-js logo is hardcoded in [styles/dmn-mixins.less](https://github.com/bpmn-io/dmn-js/blob/master/styles/dmn-mixins.less#L79). 

Making it a mix-in would give users the ability to redefine it, overriding the default. I.e. 

```
.dmn-js-logo() {
  text-decoration: none;
  display: block;

  &:after {
    .dmn-font;
    text-align: right;
    font-size: 3em;
    color: @dmn-primary;
    .transition(color .218s ease);
    text-decoration: none;
  }
 .icon-dmn.icon-dmn-js;
}
```

Not sure it could give us a better integration story.

**Comment by nikku** [comment]
Maybe we can just close this once the font is being properly isolated (via #13).

**Comment by SebastianStamm** [comment]
Can this be closed? The referenced issue has been closed. If not, what has to be done?

**Comment by nikku** [comment]
Yes, can be closed. Thanks for keeping track!
