### ISSUE TITLE
I can edit a label

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#126]
Need to add "direct editing" (diagram-js-direct-editing).

So it's possible to change the labels (name property) by double clicking the element.

Ensure that double click is not drill down anymore.

**Comment by SebastianStamm** [comment]
Double clicking is already "Goto Table View" for decisions.

**Comment by SebastianStamm** [comment]
Changing the label of a decision is already possible in the table view, but we need to update the drd (#145). Still need a way for non-decision elements
