### ISSUE TITLE
Prefix dmn-js internal fonts with dmn-

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#13]
Currently the dmn-js internal icons have the class `icon-dmn icon-foobar`. We should change that to `dmn-icon-foobar` to avoid collisions with other fonts.

**Comment by nikku** [comment]
Would it make sense to call the font `dmn-js`, as it is not about DMN but just a collection of `dmn-js`-related symbols?

**Comment by zeropaper** [comment]
Do you mean the font or the prefixes?
