### ISSUE TITLE
Table is not editable in DRD Modeler

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#131]
Currently, when you instantiate the Modeler, the decision tables and literal expressions are not editable.

Reason: The import workflow is DRDModeler --> DRDViewer --> TableViewer

Proposed Solution: When instantiating the DRDModeler, we set an options property to tell the DRDViewer to include the TableModeler instead of the TableViewer

**Comment by ricardomatias** [comment]
I've solved this additionally in #132 and added test cases.

What was missing from your solution was separating the Table Modeler from the DRD Viewer and test cases.
