### ISSUE TITLE
Values for "expressionLanguage" created by modeler are not recognized by execution engine

### ISSUE THREAD

**Issue by neuweiler** [bpmn-io/dmn-js#133]
If you specify an input expression in javascript in the modeler, the generated tag expressionLanguage="Javascript" is not recognized by the DMN execution engine. It reports that no script engine was defined. If you manually change the DMN file so it states expressionLanguage="javascript" (all lower-case) it works fine.

**Comment by SebastianStamm** [comment]
You are not restricted to the dropdown values for the expression language dialog. You can also write any string in the input field. Generally, the dmn-js library is execution-engine agnostic, but we could change the "Javascript" dropdown option to "javascript" anyway. @saig0, do you have input on this?

**Comment by neuweiler** [comment]
Ah thanks.. another option would be to make the execution engine case-insensitive when looking for the implementation of the script engine.

**Comment by saig0** [comment]
Currently, the Camunda DMN engine recognize the expression language (i.e. script engine) only if the name matches exactly. As user it would be easy if the names in the DMN modeler matches the names in the DMN engine.

**Comment by saig0** [comment]
The language names should be:

* Javascript -> javascript
* Juel -> juel
* Groovy -> groovy
* Python -> python
* Ruby -> jruby

**Comment by SebastianStamm** [comment]
@saig0, thank you :)
@neuweiler, do you want to provide a pull request for that?

**Comment by neuweiler** [comment]
@SebastianStamm : Nope, thanks. I'm already involved in other issues ([1](https://forum.camunda.org/t/decision-chaining/934) and [2](https://forum.camunda.org/t/error-in-variable-resolution-juel/1703)) and getting on Philipp's nerves ;)
