### ISSUE TITLE
Variable get's exported as informationItem (type) from dmn-moddle

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#142]

**Comment by ricardomatias** [comment]
Can no longer reproduce it.

**Comment by sielakos** [comment]
1. Start webapp enterprise edition
2. go to cockpit/decisions
3. select desert decision definition
4. click edit icon in top left corner
5. try to edit literal expression
6. during before saving open developer tools
7. request has xml like this:
<informationItem name="dessert" typeRef="string" />

**Comment by SebastianStamm** [comment]
I can confirm that the bug still exists in v0.8.0
