### ISSUE TITLE
I can edit the name and id of the definitions element

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#149]
We should add a module that displays the name and id of the definitions in the top left corner of the canvas when the DRD is displayed. Should be viewable in Viewer, editable in Modeler. Should be hidden when drilled down to a table or literal expression.

**Comment by gimbel** [comment]
AT:
- The ID of the definitions element has to be editable

**Comment by gimbel** [comment]
There is also a name-attribute that would be worth editing

**Comment by ricardomatias** [comment]
We should discuss this. I don't believe this issue should be solved by the library, but by the surrounding application.

**Comment by SebastianStamm** [comment]
I agree with @ricardomatias. Sounds very much like a property-panel thing.
