### ISSUE TITLE
I can append InputData from a Decision via contextPad

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#154]
It should be possible to add an Input Data from the context pad of a decision. The connection direction has to be inverted in that case.

**Comment by ricardomatias** [comment]
I think this would be confusing for modeling in general, but for dmn I can understand that it might have some value. We should gather more opinions.

**Comment by SebastianStamm** [comment]
@saig0 approached me with this idea last week, so I think we can count this as a +1 😄

**Comment by SebastianStamm** [comment]
The changes in the drd rules would allow InputData to be connected to other InputData. Trying to do so in the modeler throws an error in the console and breaks the modeler (connection stays attached to the cursor when though it's not dragged anymore)
