### ISSUE TITLE
Command Stack is lost when switching to DRD view

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#159]
Reproduce: 
 - make a change to the decision table of a decision
 - goto drd
 - go back to the decision again
 - undo

Problem: Change is not undone.

**Comment by SebastianStamm** [comment]
We would need to keep the command stack (and therefore probably the whole table viewer instance) of every decision that the user has opened, otherwise we would lose the command stack

**Comment by gimbel** [comment]
Can we please put this ticket back in the backlog until we have a first version of the modeler released with DRDs inside. Thanks

**Comment by nikku** [comment]
This is _by design_ until we change our minds, create some crazy mechanism and improve things.
