### ISSUE TITLE
I can set the variable name of the input expression result

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#16]
In the dmn-io UI I can change the variable name of the input expression result, which I than can use in the input entry expressions. The default is {{cellInput}} and the attribute is currently name {{camunda:output}} which will hopefully change (see CAM-4862). 

The new attribute name is {{camunda:inputVariable}}

Issue migrated from: https://app.camunda.com/jira/browse/CAM-4863

**Comment by berndruecker** [comment]
+1

**Comment by SebastianStamm** [comment]
* The popovers position is wrong: It should be above the cell not on top of it
* If I open the popover when using the Viewer, I cannot close the popover anymore. Trying to close it results in the following error message: `TypeError: modeling.editInputMapping is not a function` (The modeling module is not available in the Viewer)
* It is not possible to set the variable name when using a script
* It is not possible to save a script (it saves the Script Language, but not the actual script)

**Comment by SebastianStamm** [comment]
There is still an issue in Viewer mode (see commit comment). Also, it is currently not possible to unset the variableName, but we can open a bug ticket for that if you prefer.
