### ISSUE TITLE
Create design for expression language set for dmn-js

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#17]
It must be possible to set the expression language for input and output entries (all cells of the table body, except annotations)
Questions to answer
How does the workflow look like to open a combo-box where you can set the expression-language (context-menu on the cell, where to open the popup, styling, ...)
Design an indicator for cells which have an expression language set
Ideally, the indicator can listen to events (e.g. is a node in the DOM), so that you can open the combo-box edit when clicking on it.

Migrated from: https://app.camunda.com/jira/browse/CAM-4839

**Comment by SebastianStamm** [comment]
You can set the expression language via right-click (see #20). Indicator for non-default expression language needs to be done (if we still want this).

**Comment by nikku** [comment]
Will be implemented in latest dmn-js via https://github.com/bpmn-io/dmn-js/issues/240.
