### ISSUE TITLE
Only one table of four in downloaded drd

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/dmn-js#170]
If I create a drd with four tables and fill all the tables, in the downloaded file includes only one table. (I've saved all the missing as screenshot, but that works only in powerpoint mode)

The other three tables are only in the memory of the browser...

**Comment by nikku** [comment]
Can reproduce this. Thanks for your feedback.

**Comment by ricardomatias** [comment]
Might have been a temporary bug. It's working fine now.

**Comment by SebastianStamm** [comment]
Do we know what may have caused this temporary bug and are we sure it is fixed now? @nikku, are you still able to reproduce it?

**Comment by ricardomatias** [comment]
I could reproduce it on demo.bpmn.io

**Comment by SebastianStamm** [comment]
Could be integration in the demo.bpmn.io website. Do we update the download when the table changes? We had a similar problem in the drd-modeler from the examples repository. Could be the same cause. See https://github.com/bpmn-io/dmn-js-examples/commit/a506b37c183374ff2922861b79781b3147dd831d

**Comment by ricardomatias** [comment]
Nice catch. I'll take care of updating.
