### ISSUE TITLE
Improve Decision sizing

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#171]
Slightly increase width and height to

* [ ] Optimize for three line text
* [ ] Reduce intersection with overlay
* [ ] Use the default size in the example drd

**Comment by ricardomatias** [comment]
- Update demos

**Comment by SebastianStamm** [comment]
Examples have to be updated:
 - [ ] dmn-js-examples
 - [ ] demo.bpmn.io
 - [ ] camunda-modeler
