### ISSUE TITLE
I get assistence when editing date and time conditions

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#18]
Migrated from: https://app.camunda.com/jira/browse/CAM-4740

**Comment by SebastianStamm** [comment]
Date and Time conditions are very rarely used standalone. Most commonly, the expression would be like "before this date" or "after this date" or "only between 3 and 5pm on thursday". Therefore the assistance must be embedded in the script editor (possible solution: button or shortcut "add date at cursor position"). You could also parse the script content for date-strings and open a date-picker when the user clicks on it.

**Comment by SebastianStamm** [comment]
We should support the three basic use-cases "before", "after" and "between". The user should also get assistance when choosing one of the three operators.

**Comment by SebastianStamm** [comment]
Idea: Add option to fill the cell with a "template", that consists of:
 - the possible options "before", "after" and "between"
 - one or two (in case of between) datepickers

**Comment by gimbel** [comment]
We decided against date-pickers for the first version and will work with default values instead.

Also the editing will happen in a dialog
