### ISSUE TITLE
Output name could not be entered

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/dmn-js#189]
After editing the drd and going back to the decision table, I'm unable to enter any keystroke in the empty output name of the output column (advanced mode). I left it empty before and need a value for my decision test.

This stays even if I switch between the advanded and normal mode. Entering values to other table cells is possible.

Are you able to reproduce it?

**Comment by nikku** [comment]
Could you provide a detailed steps to reproduce list?

**Comment by ingorichtsmeier** [comment]
Unfortunately not. In the moment, as I tried a new model, everything works fine.

Could you please give me a hint, how to inspect further details, if this may occur again? Any output from the developer console? I tried it in firefox web modeler.

**Comment by nikku** [comment]
The developer console `F12` should display an error with additional context.

**Comment by nikku** [comment]
Closing this as we cannot reproduce the bug based on your report.
