### ISSUE TITLE
Internet Explorer 10 - element.focus "This command is not supported"

### ISSUE THREAD

**Issue by romero83** [bpmn-io/dmn-js#195]
Hi!

Under Internet Explorer 10 clicking on a DMN data row's cell cause:
unhandled error in event listener
Error: This command is not supported.

In EventBus.prototype._invokeListener
at returnValue = invokeFunction(listener.callback, args);
in case of event.type is element.focus

Additional information: In Microsoft Edge it is works fine.

**Comment by nikku** [comment]
This should not be an issue in IE 11, right? 

Maybe this can be fixed with a shim. We won't invest any resources in IE 10 though since we don't support it.
