### ISSUE TITLE
check for completeness / overlapping rules

### ISSUE THREAD

**Issue by StefanHoutzager** [bpmn-io/dmn-js#196]
Found this document wherein a link to a github project where a check for completeness / overlapping rules is built in. Is this maybe usble to integrate in this project?

**Comment by nikku** [comment]
Which document did you find?

**Comment by StefanHoutzager** [comment]
Ah, sorry, forgot to paste: https://arxiv.org/pdf/1603.07466v1.pdf. The link to the project is this one:  https://github.com/ulaurson/dmn-js. After I sent the question I found you have worked on the project also.

**Comment by nikku** [comment]
Yes, the guy received some guidance from us and worked on the project as part of his thesis. It is not in a state where we stuff can easily be adopted for production though :wink:.

**Comment by StefanHoutzager** [comment]
Ok, thanks for looking into this Nico!

**Comment by nikku** [comment]
Closing this for now as I do not think we'll gonna implement anything here any time soon.
