### ISSUE TITLE
Command stack doesn't work for DMN tables

### ISSUE THREAD

**Issue by akkie** [bpmn-io/dmn-js#199]
Hi,

the command stack doesn't work for DMN tables anymore. It does only work for DRDs.

I've registered a `commandStack.changed` listener on the modelers instance. And I'm sure that it had worked with previous versions without the the DRD modeler.

Best regards,
Christian

**Comment by ricardomatias** [comment]
Hello @akkie,

there are actually two command stacks, one for DRD modeling and one for table modeling. You need to do the following:

```
var DmnJS = require('dmn-js/lib/Modeler'),
      modeler = new DmnJS();

// DRD command stack
modeler..on('commandStack.changed', function(event) {});

// table command stack
modeler.table.on('commandStack.changed', function(event) {});
```

This means that if you want to interact with a service from a DMN Table, you need to do it through `modeler.table`.

I'm adding a ticket to add some documentation about it to the readme.

**Comment by akkie** [comment]
Great! Thanks!

**Comment by akkie** [comment]
@ricardomatias 
Can it be the case that the command stack for the table will be cleared if I switch the view? For the DRD all works expected if I switch to the table and back. 

The Camunda Modeler has the same behavior.

**Comment by ricardomatias** [comment]
Yes, that's intended behaviour the moment. In the future, we will tackle this [issue](https://github.com/bpmn-io/dmn-js/issues/159).
