### ISSUE TITLE
I can specify the expression language of inputEntry and an output entry

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#20]
We are talking about cells. 

AT:
- I can specify the expressionLanguage of an inputEntry
- I can specify the expressionLanaguage of an outputEntry
- Uses correct url for FEEL

Defaults:
- inputEntry: FEEL
- outputEntry: Juel
(-input expressions: Juel)

Migrated from: https://app.camunda.com/jira/browse/CAM-4695

**Comment by jonashackt** [comment]
+1 Our customer wants to use Groovy to call some complex Javalogic from within a Decisiontable - for now you have to edit the dmn.xml yourself to add the expressionLanguage-Definition to your Rule:
```
 expressionLanguage="Groovy"
```

**Comment by bdot** [comment]
+1

**Comment by berndruecker** [comment]
+1
