### ISSUE TITLE
DRD in IE11 input and output column mixed up

### ISSUE THREAD

**Issue by felix-mueller** [bpmn-io/dmn-js#201]
When using DRDs in IE11 with dmn-js modeler within DMNs the first input column is mixed up with the first output column. The same DRD is working fine in Firefox and Chrome. 
Please check this URL: https://camunda.org/dmn/simulator/ and especially the table "Beverages".

I am not sure what is the root cause as I haven't looked deeper into it, but I get a Script Error in IE11 here:

https://github.com/bpmn-io/table-js/blob/363d2327f927f1af7247e354889e1f3d94f5f566/lib/features/interaction-events/InteractionEvents.js#L115

'Object doesn't support property or method contains'.
Event.target is a HTMLDocument object.

Best
Felix

**Comment by berndruecker** [comment]
See also https://app.camunda.com/jira/browse/CAM-7482 in cockpit (when done)

**Comment by falko** [comment]
A customer reported this also in Microsoft Edge 38.14393.0.0 (Microsoft EdgeHTML 14.14393)

**Comment by nikku** [comment]
@SebastianStamm Please let @philippfromme or anyone else from the team review this.
