### ISSUE TITLE
Opening DRD with Text Annotation results in connection not being cropped

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#203]
Reproduce
* Model DRD shown below
* save to disk
* open

![unbenannt](https://cloud.githubusercontent.com/assets/7633572/23551865/10b1cc38-0019-11e7-91b1-34b7bc85e314.PNG)

**Comment by nikku** [comment]
Still an issue with `dmn@2`.

**Comment by philippfromme** [comment]
I can still reproduce this.

**Comment by barmac** [comment]
OK, I tried with a bigger distance between the elements and it's still broken.

**Comment by philippfromme** [comment]
The reason the association is not cropped correctly is that it was created with a version of dmn-js that [didn't set the cropped DI waypoints after a connection of the type `dmn:Association` was created](https://github.com/bpmn-io/dmn-js/blob/57a737afc4bc2d16beb44dd95bd01560410be86c/packages/dmn-js-drd/src/features/modeling/DrdUpdater.js). The `DmnUpdater` has since been completely overhauled and the behavior is not reproducible with current versions of dmn-js anymore.

**Comment by philippfromme** [comment]
Actually, there's one possible improvement. An [unnecessary waypoints update](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-drd/src/features/modeling/DrdUpdater.js#L147) can now be removed. It's a leftover from before the refactoring.
