### ISSUE TITLE
Usability: Expression Popup overlaps column

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#21]
The input expression popup overlaps the header of the current column.
This is not ideal because the user looses the context.

AT:
- the input expression popup does not overlap the current column

Note: if the popup is placed to the right of the column (like the datatype popup) it might not always fit on the screen

Migrated from: https://app.camunda.com/jira/browse/CAM-4380

**Comment by philippfromme** [comment]
Not an issue in latest dmn-js.
