### ISSUE TITLE
Layout error when render dmn-js

### ISSUE THREAD

**Issue by santosguilherme** [bpmn-io/dmn-js#212]
Dmn-js is rendering without the styles, which should be in the dmn-js.css file, however this file does not exist.

The only files that exist are the dmn.css and the dmn-embedeed.css, which are in the `node_modules/dmn-js/assets/dmn-font/css` directory.

Where is the file that I should import (dmn-js.css)? Or do I have to generate from the `styles/dmn-js.less`?

This `dmn-js.css` compiled file from `styles/dmn-js.less`, should not come as a dependency?

![dmnj-js_witherror](https://user-images.githubusercontent.com/8635147/28032007-709e4baa-657f-11e7-8fe0-8ae6d8cd218b.png)

**Comment by nikku** [comment]
The new `dmn-js@2` ships with pre-built styles.
