### ISSUE TITLE
Connection is different depending on how it's created

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#216]
![2017-08-04_13-51-33](https://user-images.githubusercontent.com/7633572/28967633-5dd69b52-791c-11e7-845f-04d6540396fd.gif)

**Comment by nikku** [comment]
This is related to https://github.com/camunda/camunda-modeler/issues/461.

Closing this issue for now, as we don't plan to improve the situation any time soon.

We welcome contributions and pointers regarding this though!
