### ISSUE TITLE
Redesign controls area

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#217]
Currently:
<img width="960" alt="tjs-controls-old" src="https://user-images.githubusercontent.com/7633572/28969884-aabb606a-7926-11e7-99c0-988c510a3d7a.png">

Proposal:
<img width="960" alt="tjs-controls-redesign" src="https://user-images.githubusercontent.com/7633572/28969889-b1600790-7926-11e7-9cf0-a9db5d152262.png">

**Comment by nikku** [comment]
Will be reworked in new dmn-js anyway.
