### ISSUE TITLE
Add validation for allowedValues

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#22]
AT:
- [ ] In the datatype input dialog, if the same allowed value is entered twice, the fields are highlighted to indicate a warning
- [ ] when closing an input dialog that contains duplicate values, discard the duplicate (only save string once)

Migrated from: https://app.camunda.com/jira/browse/CAM-4367

**Comment by nikku** [comment]
We're distinguishing _allowedValues_ and _custom values_. On top of that we don't plan to add additional validation in the near future.
