### ISSUE TITLE
Question: How to set an id to a table?

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#227]
Previously, I could assign an id like this to a table:
```
        modeler.get('tableName').setId(id);
```
Now, It does not work.

What's the new way to do the same to a given table?

**Comment by rbatllet** [comment]
Is it correct?
```
        modeler.get('table').get('tableName').setId(id);
```

**Comment by philippfromme** [comment]
Yes, this is correct. We added DRD modeling to dmn-js a while ago. The table is now part of the modeler so you can either use `modeler.get('table')` or `modeler.table`.
