### ISSUE TITLE
Possible bug: getAll() does not show all the elements

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#229]
If I have only ONE decision table and I want all the elements, then I do:

```
        const elementRegistry = modeler.get('elementRegistry');
        const allValues = elementRegistry.getAll();
```
Only the "dmn:Definitions" type is returned but not my "dmn:Decision" one. 
In order to get it, I've to click on "show DRD" button, then it is returned with the "dmn:Definitions" type!

**Comment by nikku** [comment]
This is due to the fact that we're dealing with different editors. For each editor `elementRegistry` is something else and other elements are visible/editable.
