### ISSUE TITLE
I can restrict table editing (Example)

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#24]
AT:
- there exists a documented example showing how I can restrict editing in the DMN table editor
- in the example I can only change
  -- allowedValues ("add a new customer status")
  -- change the value of inputEntries and output entries
  -- everything else cannot be edited

Migrated from: https://app.camunda.com/jira/browse/CAM-4204

**Comment by CarstenEnglert** [comment]
As this is matching our use case for advanced system configurations, I'd like to see that as well.
Is there any plan on providing such an example in the foreseeable future?

**Comment by nikku** [comment]
No concrete plans yet. Your feedback increases the likelihood that we are going to work on this, though :wink:.

**Comment by nikku** [comment]
Looking into this issue once again, this is not an easy pick to implement.

Because of this and because of the fact that we have no intention to implement this any time soon I'll close this issue as won't fix.

We may re-validate things based on community feedback.

**Comment by CarstenWickner** [comment]
We were still hoping for this to be possible.
Pity.

**Comment by nikku** [comment]
We're always happy to receive contributions on this.
