### ISSUE TITLE
I can drag and drop rows/columns

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#241]
* [x] add drag handle for rows and columns (shows on mouseover)
* [x] Show drag preview (current row / column HTML) and drop indicator
* [x] Move selection on drop
* [x] `ESC` to cancel drag operation

**Comment by philippfromme** [comment]
Test cases depending on drop position fail in PhantomJS.

**Comment by nikku** [comment]
I've finished my review, carried out the related changes + a little bit of cleanup (better code structuring / readability improvements).

Fixed the drop into textfield bug, too!

Please review the stuff, squash my commits and merge the changes.
