### ISSUE TITLE
I can use keyboard bindings

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#252]
* [ ] Keyboard shortcuts for UNDO / REDO work consistently in literal expression and decision table
* [ ] Cell navigation like in Excel and other table editors 
  * [ ] `Tab`: navigate horizontally (`+ SHIFT` to move to left)
  * [ ]  `ENTER`: navigate vertically (`+ SHIFT` to move up)
  * [ ] `CTRL + ENTER` adds line break in current cell 
* [ ] Integrate keyboard navigation with focus handling

**Comment by nikku** [comment]
Assessment of current state:

* Undo / Redo does not work from edit menus
* Undo / Redo does not work properly in decision ID editor
