### ISSUE TITLE
Support different editors (decision tables, literal expressions, boxed context, ...)

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#254]
In the future we might want to support more editors for DMN 1.1 elements. Therefore dmn-js should not have the decision table modeler as a property but a list of editors that can edit a specific element. Decision tables and literal expressions can then be split into seperate editors.

**Comment by nikku** [comment]
This is properly implemented with the current dmn-js architecture. Editors are pluggable and may be shipped with dmn-js.
