### ISSUE TITLE
I can decorate cells

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#258]
Be able to hook into cell rendering in order to render additional stuff:

```javascript
<td>
  <!-- decorators -->
  <span>Content</span>
  <!-- decorators -->
</td>
```

Necessary for #239 and #241.

**Comment by nikku** [comment]
We got the basic mechanisms in place to perform decoration.

With #252 merged it gets even simpler via the `ComponentWithSlots` concern.
