### ISSUE TITLE
I can set input values for an input expression

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#27]
AT:
 - allowed values can be set for input expression (both script and expression variants)
 - ~~It is available for all input types, not just for strings~~ Just for Strings

**Comment by zeropaper** [comment]
Just a note, the parsing of the value (into a list) does not work as expected.
Some item of the list lose their first or last char (in the screnshot below, the first allowed value should be "abcd" instead of "abc").
![image](https://cloud.githubusercontent.com/assets/65971/17479267/d9ffde0e-5d71-11e6-9403-3942d3ddf1d9.png)

**Comment by zeropaper** [comment]
Styling is done, I think @ricardomatias is supposed to take it from here.

**Comment by menski** [comment]
Could we not name this allowed values as from the DMN perspective these are input resp. output values and allowed values is something different.

**Comment by zeropaper** [comment]
Daniel mentionned that the naming wasn't correct.. but couldn't say what would be correct. So, sure, should be done.

**Comment by gimbel** [comment]
Please make sure, that we use the correct naming. 

WRONG: Allowed Values (that's how it used to be called)
Corrent: Input Values

**Comment by ricardomatias** [comment]
@SebastianStamm I don't see any new push on the branch. Perhaps you can take a look at this feature after merging my test branches and add some integration tests.

**Comment by SebastianStamm** [comment]
@ricardomatias The new commits are on the `27-allowed-values` branch, e.g. https://github.com/bpmn-io/dmn-js/commit/449ac535e4fa0c01bf1a0d359e9af0936a3865e8

I would like to have a look at how to get your test branches in this feature branch and how to get this feature branch on master together.

**Comment by SebastianStamm** [comment]
Strings should also produce a popup menu in simple mode, allowing for more complex constructs (like "or" and "not" operations)

**Comment by SebastianStamm** [comment]
@ricardomatias could you add a list of review hints and problems you found to this ticket? So I don't forget anything when I fix the remaining issues.

**Comment by SebastianStamm** [comment]
- [ ] type switching from sting to boolean --> cell content is now "bronze"[expression]
- [ ] add test cases for add allowed value and remove allowed value handler
- [ ] persist input for new string value on dialog close
