### ISSUE TITLE
Fix project logo positioning

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#272]
Currently positioning of the project logo in the upper right corner is quite hacky. The logo should always be visible in the upper right corner of the decision table container.

**Comment by nikku** [comment]
What is hacky about it? What would be a better position?

**Comment by nikku** [comment]
We should either fix this issue or close this ticket forever :heart:.

**Comment by nikku** [comment]
Shouldn't we apply `display: table` as part of the offical CSS?
