### ISSUE TITLE
Monorepo: Switch to dependendent versioning?

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#273]
Right now we version independently, due to [this configuration](https://github.com/bpmn-io/dmn-js/blob/master/lerna.json#L6).

Versioning all packages together would allow us to get rid of [this mess](https://github.com/bpmn-io/dmn-js/releases).

**Comment by philippfromme** [comment]
+1

**Comment by nikku** [comment]
Doing it!
