### ISSUE TITLE
Inserting line breaks results in text duplication

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#279]
Due to Inferno not being able to handle content-editable elements after you insert line breaks (which depending on the browser wraps every inline in a `<div>` or `<p>` or inserts a `<br>`) after you insert a line break only the first text node in that content-editable element will be updated which leads to duplication.

Camunda Modeler issue: https://github.com/camunda/camunda-modeler/issues/709

**Comment by nikku** [comment]
We must think of a different solution here, as using `dangerouslySetInnerHtml` will make us prone to XSS. Cf. [this comment](https://github.com/camunda/camunda-modeler/issues/709#issuecomment-357956104).

**Comment by nikku** [comment]
Ready for second review.

**Comment by nikku** [comment]
Needs additional testing in IE 11 and Edge.
