### ISSUE TITLE
I can simple edit number

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#284]
Related to #243

**Comment by nikku** [comment]
Review hints:

* Please rebase on current master, configure editor to strip trailing spaces and fix lint errors
* `BUG`: Input `.1` (a valid number in FEEL) in `Range -> End`. Reopen simple edit dialog. Number turned into `1`
* [Code related comments](https://github.com/bpmn-io/dmn-js/commit/38ba4490ac596702d6279ca39c5401da39acd810#comments)

**Comment by philippfromme** [comment]
Done
