### ISSUE TITLE
Question: How to generate the bower version from dmn-js sources

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#291]
I need to get the bower version of the current dmn-js version but I can't find the way to do so.

The current dmn-js is extremely outdated (or abandoned) (https://github.com/bpmn-io/bower-bpmn-js). The last version was 0.10 but it was reverted to 0.9.1.

I would very much appreciate any help or guidance.

**Comment by nikku** [comment]
This is related to https://github.com/bpmn-io/bower-dmn-js/issues/2, right? As mentioned in [our project forum](https://forum.bpmn.io/t/dmn-js-1-1-1-usage/1969/5) we're working on stabilizing the library before building a pre-packaged distribution.

**Comment by rbatllet** [comment]
What is the last stable version, 0.10 or the 0.9.1, right now?

**Comment by philippfromme** [comment]
The last stable version is 0.11.0. However the last version available in bower-dmn-js is 0.9.1.

**Comment by nikku** [comment]
You may execute `npm run distro` on `dmn-js@0.11` to build the current stable pre-packaged distribution yourself.

**Comment by nikku** [comment]
We'll provide updated examples and a new pre-packaged distribution via https://github.com/bpmn-io/dmn-js/issues/302.
