### ISSUE TITLE
Current releases of dmn-js and table-js are incompatible regarding the babel-plugin-inferno dependency

### ISSUE THREAD

**Issue by Hubel** [bpmn-io/dmn-js#305]
Your projects are currently in an incompatible state which I cannot resolve consuming the published NPM packages.

My dependency chain is
```
-- dmn-js@1.3.1
  | A dmn toolkit and web modeler
  `-- dmn-js-decision-table@1.3.1
    | A decision table view for dmn-js
    `-- table-js@1.4.1
        A blazing fast library for viewing and editing tables.
```
where `table-js` is the only package yet published with a dependency to **`babel-plugin-inferno@^4.0.0`**.
The others are are still depending on version **`^3.x.x`** of the inferno plugin. That causes the transpiled code to be nonexecutable (`TypeError: (0 , _inferno3.createComponentVNode) is not a function`).

I'm aware that this is an ongoing upgrade so you surely have the steps in mind required to get the depending projects leveled again.
If you're proceeding to prepare a major release I just wanted you to know that there might be a bugfix release required with a consistent state regarding the inferno version.

**Comment by nikku** [comment]
You are absolute correct.

To better comply with [semver](https://semver.org/) we should have published table-js with the changes as a new major version.

As a workaround I'd suggest you to manually pin the `table-js` version in your project to `1.3.x`. This should allow you to use `dmn-js @1.3.x`.

The latest master of `dmn-js` will be compatible with the new table-js.

We're sorry for the inconvenience this may cause to you.

**Comment by nikku** [comment]
We'll do the following to improve:

* [ ] make `dmn-js@1.3` installable again by depending on `table-js@~1.3.0`
* [ ] communicate `dmn-js@1` as unstable in our `README` (`dmn-js@2` will be the next stable version, `v0.11.0` is the previous one)
