### ISSUE TITLE
Clicking on already selected cell results in cell not being editable anymore

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#311]
Reproduce:

1. Click on cell - cell is selected, caret is visible
2. Click on cell again - cell is still selected, caret is gone

![foo](https://user-images.githubusercontent.com/7633572/36383703-3ce577c0-158d-11e8-8b44-4005387e3c43.gif)

**Comment by nikku** [comment]
This is fixed on master already.

![foo](https://user-images.githubusercontent.com/58601/36391678-cc3e56de-15a7-11e8-8f75-3d0eae636a39.gif)
