### ISSUE TITLE
DMN XML get wrongly saved

### ISSUE THREAD

**Issue by alex-zak** [bpmn-io/dmn-js#312]
**Actual Situation**
I found out that the editor creates wrong XML in a specific situation. 
Normally empty cells are added to the XML in the following way:
```
        <inputEntry id="UnaryTests_1mtk1hq">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_087aham">
          <text></text>
        </outputEntry>
```
But the Modeler sometimes just don't generate this code. with leads to errors in the interpretation and if you reopen the DMN values are moving from cell to cell.

**Steps to Reproduce**
Preconditions:
Use a DMN having at least 2 inputs
Use a DMN having a Date Output (See attachment)
Use the Simple Mode
Steps:
Add a new Input Column Name I3
Add a new Row
Already this row behaves incorrect the popups are not show is a mix of simple and complex mode.
Add in Input I3 a value X (Input 1, Input 2 and Output are empty) 
Please note that the value disappear after pressing one letter and is now shown as an [expression] 
User has to change to advanced mode to work
Save
Check the XML 

Expected Result
```
        <rule id="row-623882880-16">
        <inputEntry id="UnaryTests_0hdpbsm">
          <text></text>
        </inputEntry>
        <inputEntry id="UnaryTests_0fpl36n">
          <text></text>
        </inputEntry>
        <inputEntry id="UnaryTests_0fpl473">
          <text><![CDATA["X"]]></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_09mdw72">
          <text></text>
        </outputEntry>
      </rule>
```

Actual Result (see attachment)
```
      <rule id="row-623882880-31">
        <inputEntry id="UnaryTests_169ob0n">
          <text></text>
        </inputEntry>
        <inputEntry id="UnaryTests_0u443gz">
          <text>X</text>
        </inputEntry>
      </rule>
```

[IssueExamplesDMN.zip](https://github.com/bpmn-io/dmn-js/files/1740203/IssueExamplesDMN.zip)

Thanks a lot for your help we are using DMN heavily in or project between IT and our Business and it is opening up a much better collaboration.

**Comment by Paraiso83** [comment]
Issue reproducible in the last bower available version [v0.10.0](https://github.com/bpmn-io/bower-dmn-js/tree/v0.10.0)

**Comment by nikku** [comment]
Can you reproduce the bug with the latest pre-release version (available at [demo.bpmn.io/dmn](https://demo.bpmn.io/dmn))?

**Comment by alex-zak** [comment]
yes kind of. 
the new editor also do not generates the empty "Text" tags but he generates the at least a "Entry" tag for every cell. 
```
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd" xmlns:biodi="http://bpmn.io/schema/dmn/biodi/1.0" id="definitions" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="decision" name="Test">
    <extensionElements>
      <biodi:bounds x="150" y="150" width="180" height="80" />
    </extensionElements>
    <decisionTable id="decisionTable">
      <input id="input1" label="">
        <inputExpression id="inputExpression1" typeRef="string">
          <text>I1</text>
        </inputExpression>
      </input>
      <input id="InputClause_06q4m8a">
        <inputExpression id="LiteralExpression_1mo62kn" typeRef="string">
          <text>I2</text>
        </inputExpression>
      </input>
      <input id="InputClause_0w92eq5">
        <inputExpression id="LiteralExpression_118le2p" typeRef="string" />
      </input>
      <output id="output1" label="" name="O1" typeRef="date" />
      <output id="OutputClause_0gcnky0" name="O2" typeRef="string" />
      <rule id="DecisionRule_0y9x8dv">
        <inputEntry id="UnaryTests_08t1g3z">
          <text><![CDATA["A"]]></text>
        </inputEntry>
        <inputEntry id="UnaryTests_0lsa9ia" />
        <inputEntry id="UnaryTests_11pj1bu" />
        <outputEntry id="LiteralExpression_05s36v2">
          <text><![CDATA[date and time("2018-02-21T00:00:00")]]></text>
        </outputEntry>
        <outputEntry id="LiteralExpression_195qv1r" />
      </rule>
      <rule id="DecisionRule_17iw3fk">
        <inputEntry id="UnaryTests_1aao91z" />
        <inputEntry id="UnaryTests_1qpglcs">
          <text><![CDATA["B"
]]></text>
        </inputEntry>
        <inputEntry id="UnaryTests_1e8xe4u" />
        <outputEntry id="LiteralExpression_0qc8di3">
          <text><![CDATA[date and time("2018-02-21T00:00:00")]]></text>
        </outputEntry>
        <outputEntry id="LiteralExpression_0lbl6h8" />
      </rule>
      <rule id="DecisionRule_0whunq1">
        <inputEntry id="UnaryTests_0neq0fy" />
        <inputEntry id="UnaryTests_0bhup9q" />
        <inputEntry id="UnaryTests_0m9ny7a">
          <text><![CDATA["C"
]]></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_04gm363" />
        <outputEntry id="LiteralExpression_1o3585o" />
      </rule>
    </decisionTable>
  </decision>
</definitions>
```
As we are licencing a enterprise version of Camunda maybe we using the wrong communication channel to you. If so please help us to get the communication right. thx 🙇

**Comment by nikku** [comment]
Please talk to Camunda via the available support channels then. 

Help them out by pointing to this issue.

**Comment by nikku** [comment]
> Please talk to Camunda via the available support channels then.

(If your usage of Camunda products is affected by this bug).

**Comment by nikku** [comment]
This will be addressed via https://github.com/bpmn-io/dmn-js/commit/24c3897b96b06acd3df120b861a0a288c62518c2 and fixed in the next dmn-js alpha release.

**Comment by alex-zak** [comment]
Thx a lot :) yes as the business is using the offline modeler to create DMNs we had a lot of confusion from this bug. Currently they stopped using the simple mode to prevent this behavior but people forget ...
We will address the issue by the other channel and point to this fix. Big thx from us.
