### ISSUE TITLE
Implement Decision Table Rules

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#320]
Rules make it easier to check if certain modeling operations can be executed or not.

**Comment by nikku** [comment]
Do we know what we'd like to do here?

I.e. which operations should be double checked via rules and which should not?

**Comment by nikku** [comment]
Where is this implemented?

**Comment by nikku** [comment]
Found it. 

Did you checkout the [build failure on Travis](https://travis-ci.org/bpmn-io/dmn-js/builds/347698312)? Looks related to your changes.
