### ISSUE TITLE
Output type cell does not update on change

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#323]
__Reproduce__

* Open diagram with output clause
* Edit output type via header
* __Table values does not update__

__Screencast__

![bug](https://user-images.githubusercontent.com/58601/37413767-02cc04a0-27a8-11e8-9faa-fffae98816fc.gif)

__Expected__

* Table value updates on output type change

**Comment by philippfromme** [comment]
I think this is another issue due to missing keys. I can only reproduce it once I've rearranged columns (e.g. drag and drop).
