### ISSUE TITLE
Simple String Edit breaks click handlers

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#325]
Using _Simple String Edit_ corrupts click handlers.

__Reproduce__

* Open Simple String edit menu
* Click inside the edit menu
* Close edit menu (or keep open)
* Add new row by clicking on last row
* :tada:

__Screencast__

![bug](https://user-images.githubusercontent.com/58601/37509918-a7dff6de-28f9-11e8-8d08-37f8b1a8b07c.gif)

**Comment by nikku** [comment]
__Note:__ Consistently adds 1000 columns, too. :cake:

**Comment by philippfromme** [comment]
This is actually not an issue due to simple string editing. It also occurs in many other cases.
