### ISSUE TITLE
dmn-js-decision-table.css overwrites table styles

### ISSUE THREAD

**Issue by kroeder** [bpmn-io/dmn-js#328]
Hi,

your css file in dmn-js-decision-table (/assets/css/dmn-js-decision-table.css) is causing some trouble in one of our projects because you overwrite tables in general and not just your component

```
table tbody {
  border: solid 2px #444;
}

td {
  white-space: pre;
}

table tfoot {
  border-right: solid 2px #eee;
  border-bottom: solid 2px #eee;
  border-left: solid 2px #eee;
}

table tfoot td {
  border: solid 1px #eee;
}
```

Can you make this scoped? Otherwise we must carry a couple of `!important` overwrites in order to avoid our tables to be broken

**Comment by nikku** [comment]
Which version of dmn-js are you referring to? Do you mind providing a PR that adds the relevant scoping?
