### ISSUE TITLE
Add feel-scala as expression language

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/dmn-js#333]
As a user of the Feel-Scala community extension, I would like to add a different expression language. (It's feel-scala here)

![grafik](https://user-images.githubusercontent.com/7870843/37825959-f80c3922-2e91-11e8-982c-40af64f111e8.png)

Best would be to open the drop down to enter free text.

**Comment by nikku** [comment]
This will be fixed via https://github.com/bpmn-io/dmn-js/issues/322.

We'll not add more pre-wired, custom expression languages to the drop-down.

**Comment by nikku** [comment]
Implemented via https://github.com/bpmn-io/dmn-js/pull/441.
