### ISSUE TITLE
Change order of Input Expression/Name and Label

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/dmn-js#346]
The Label can technically be omitted. But if you add an input expression "guests with children?", which looks fine on the first glance, (see this table: https://github.com/ingorichtsmeier/dmn-test-tool/blob/master/dmn-excel-tester/src/test/resources/exampleEvaluation/modeler12_1.dmn) you will get an error when you evaluate it: https://github.com/ingorichtsmeier/dmn-test-tool/blob/master/dmn-excel-tester/src/test/java/com/camunda/consulting/dmn_excel_tester/example/ExampleEvaluations.java#L169-L187

So, the Label is most important for business users and should be entered first. Then you could add an input expression for evaluation (or generate it on the fly as the simulator (https://camunda.com/de/dmn/simulator/) or the dmn-test-tool (https://github.com/ingorichtsmeier/dmn-test-tool) do.

Both, the Label and Input Expression should be visible all the time.

**Comment by ingorichtsmeier** [comment]
Addition: I never used the input variable since we support DMN. 

Maybe you could swith the display of the inputVariable with the Input Expression?

**Comment by nikku** [comment]
Could you attach a screenshot providing a little bit more context?

**Comment by ingorichtsmeier** [comment]
This table won't work:

![grafik](https://user-images.githubusercontent.com/7870843/38673786-92f7869c-3e52-11e8-9e96-efb992191b1b.png)

This table will work, but you have to use the context menu to inspect the input expression:

![grafik](https://user-images.githubusercontent.com/7870843/38673910-fba4f7d8-3e52-11e8-96fa-5c6b1ea2577b.png)

This table looks nice, but I have never used the input variable before:

![grafik](https://user-images.githubusercontent.com/7870843/38673950-22027a0e-3e53-11e8-837e-57fc8aa88c1c.png)

**Comment by ingorichtsmeier** [comment]
OK, lets keep the focus of this ticket on the order of the labels of the pop-up dialogues. (as the title of the ticket says)

The user should enter the **input/output label** first

and then the **input expression/output name**.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/395.
