### ISSUE TITLE
Data attributes in decision table viewer input headers and output cells

### ISSUE THREAD

**Issue by siffogh** [bpmn-io/dmn-js#357]
In Camunda BPM Cockpit, we use such data attributes to be able to modify input headers and output cells and in order to add values to them.

These data-attributes are already present in the Modeler but it would be necessary for us to have them in the Viewer.

**Comment by nikku** [comment]
Would you be open to file a PR adding the required functionality?

* [ ] data-* attributes in viewer
* [ ] [tests](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-decision-table/test/spec/features/decision-table-head/DecisionTableHeadSpec.js#L13) that verify the attributes exist

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/dmn-js/pull/358.

**Comment by nikku** [comment]
Released as `v4.4.0`.
