### ISSUE TITLE
Column dragging not working if no rule rows

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#36]
Seems like the column dragging in dmn-js falsefully assumes there is always a row.

Reproduce:

* Create new DMN diagram at [demo.bpmn.io/dmn/new](http://demo.bpmn.io/dmn/new)
* Try to drag column
* Check console

The logged JavaScript error is:

```
app.js:1592 Uncaught TypeError: Cannot read property 'cloneNode' of null
    Drag.createDragVisual @ app.js:1592
    Drag.updateVisuals @ app.js:1493
    (anonymous function) @ app.js:1447
```

**Comment by pedesen** [comment]
+1 for a fix :muscle:
