### ISSUE TITLE
DMN editor becomes unusable in Interner Explorer 11

### ISSUE THREAD

**Issue by eugene-moroz** [bpmn-io/dmn-js#361]
While using DMN editor version 4.4.0 (same with 5.1.0), it becomes unusable when right-clicking with a mouse on any place in editor. Console showed following stacktrace
![right_click](https://user-images.githubusercontent.com/5734397/42555829-d27e49f8-84e9-11e8-800a-9e3a17f1c53b.png)

There also couple styling issues which appear also only In IE:
- (1) edit icon is not shown next to the cell but appears to the top
- (2) outline of a selected cell is not correct
![wrong_position_of_edit](https://user-images.githubusercontent.com/5734397/42555925-2fd45232-84ea-11e8-85c7-3f9ac994339b.png)

All mentioned issues do not occur on any other browser but IE11

**Comment by CarstenWickner** [comment]
Another  issue in IE11 is that when clicking on an item in the script/language dropdown, the whole surrounding dialog is closed and the selection is ignored. Workaround is to type the name of the script/language in the dropdown input field.

**Comment by nikku** [comment]
@philippfromme Can you reproduce these issues?
