### ISSUE TITLE
Allow entering line breaks via Enter in Input Expression Script

### ISSUE THREAD

**Issue by CarstenWickner** [bpmn-io/dmn-js#362]
Prior to the rewrite of the DMN editor, one could press the enter/return key while focusing the "Input Expression" textarea (e.g. while entering a multi-line JavaScript expression), which inserted a line break as expected.

However with the new DMN editor, pressing the enter/return key now closes the dialogue. Inserting a line break is only possible by copy-pasting it from somewhere else (e.g. a text editor) into the "Input Expression" textarea.

This is pretty inconvenient at the moment but should hopefully an easy fix.

**Comment by nikku** [comment]
Did you try `CTRL + ENTER`? We adopted it consistently across the whole table to yield a line break.

**Comment by CarstenWickner** [comment]
Yes, `Ctrl + Enter` works.
Just need to get used to it then (after it was different in the previous editor).

That means this is not a bug here, but rather an improvement suggestion since closing the dialog when pressing Enter is still not that meaningful.

**Comment by nikku** [comment]
Closing dialogs / overlays on `ENTER` is the general usability pattern we've implemented.
