### ISSUE TITLE
Deletion of characters in DMN editor is ignored in IE11

### ISSUE THREAD

**Issue by rafaeltc** [bpmn-io/dmn-js#369]
It is not possible to edit a field using DMN editor in IE11 by deleting existing characters (i.e. only deleting, not adding any new charaters). 

Test case:
1. Create new diagram
2. Edit column by adding content
3. Download DMN file
4. Edit a column solely by deleting content (backspace/delete)
5. Download DMN file and confirm that the deleted characters are still displayed in the DMN file

Test executed in https://bpmn.io at 30th August 2018 (bpmn-io-demo - 2018-08-28).

**Comment by nikku** [comment]
Thanks for reporting this issue.
