### ISSUE TITLE
Add Aggregation LIST to hit policy COLLECT

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#370]
This feature is missing in dmn-js@2. It was available in dmn-js@0.x.x.

To investigate: Is there a default aggregation defined in the spec? If not, we should make it easier to remove the aggregation, too: https://github.com/bpmn-io/dmn-js/issues/389.

---

Required by https://github.com/camunda/camunda-modeler/issues/900

Related to https://github.com/bpmn-io/dmn-js/issues/389

**Comment by StephenOTT** [comment]
+1 to get this fixed up

**Comment by barmac** [comment]
This will be implemented as _NO LIST AGGREGATION_.
