### ISSUE TITLE
Layout breaks when having very long decision names

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#373]
* text doesn't wrap
* text covers _View DRD_ button

__Hint:__ This is cause by `white-space: pre;`.

<img width="960" alt="fail" src="https://user-images.githubusercontent.com/7633572/45613053-50829b00-ba65-11e8-8e76-041869a4fe77.png">

**Comment by velykov** [comment]
Thank you for this issue

**Comment by velykov** [comment]
Now not only long name breaks layout, also long text in bottom area with script breaks layout.
