### ISSUE TITLE
Input expression UI changes back to single line after typing

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#377]
Reproduce:

1. Edit empty input expression
2. Change to script (which only makes a difference in the UI)
3. Type

Expected Behavior:

1. UI doesn't change back to single line

Actual Behavior:

1. UI changes back to single line after changes have been commited

![2018-10-18_11-10-18](https://user-images.githubusercontent.com/7633572/47144070-e872df00-d2c6-11e8-8444-6b7332aaed1b.gif)

**Comment by MaxTru** [comment]
Cannot be reproduced with dmn-js@9.x.x
