### ISSUE TITLE
Empty DMN table looks broken in Firefox

### ISSUE THREAD

**Issue by mschoe** [bpmn-io/dmn-js#380]
__Describe the Bug__

Tables in firefox looks broken. 

__Steps to Reproduce__

1. Go to https://demo.bpmn.io/dmn/new
2. add and remove a column

__Expected Behavior__

Table will be rendered correctly. 

__Environment__

 - Browser: FF 63
 - OS: linux

**Comment by barmac** [comment]
notice: adding a row to table fixes the layout

same problems on MacOS 10.14.1/ FireFox 60.3.0esr

**Comment by barmac** [comment]
This might be useful: https://stackoverflow.com/questions/34038326/table-rows-border-hidden-in-firefox-only

**Comment by barmac** [comment]
@mschoe Could you please check if it works the same way on linux?

**Comment by nikku** [comment]
@barmac Workaround is the same on linux.

**Comment by frycon** [comment]
This is a know firefix bug and probably the oldest active bug in modern history :D
@see https://bugzilla.mozilla.org/show_bug.cgi?id=217769
@see https://stackoverflow.com/questions/33168178/why-does-firefox-not-render-border-of-table-with-empty-tbody

Workaround: add a rule to dmn-js-decision-tables.css:

```
.dmn-decision-table-container .tjs-table > tbody:empty {
    display: none;
}
```

**Comment by barmac** [comment]
Thank you for your input. I'll check out the solution that you proposed and if it works correctly we can quickly ship a bugfix.
