### ISSUE TITLE
Context menu does not stay open on Firefox

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#381]
__Describe the Bug__

It is not possible to use the context menu (right click).

__Steps to Reproduce__

1. Go to https://demo.bpmn.io/dmn/new
2. try to open context menu via right click

__Expected Behavior__

Context menu does not disappear on mouse up (right click).

__Environment__

 - Browser: FF 63
 - OS: linux

**Comment by daniloff200** [comment]
I've used FF 75.0 on Linux, looks like, this issue was fixed on FF side, or, here :)
Can't reproduce it right now

**Comment by nikku** [comment]
Thanks for the heads up. Closing this then.
