### ISSUE TITLE
type property overridden when viewer.created is fired

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#385]
When a viewer is created [an event is fired](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-shared/src/base/Manager.js#L469). Its `type` property is [overridden by the event bus](https://github.com/bpmn-io/diagram-js/blob/master/lib/core/EventBus.js#L259). This is a known issue, using a `type` property is therefore not possible. We should rename it.

**Comment by nikku** [comment]
Usage of `type` property across our libraries:

* `bpmn-js`: 1
* `dmn-js` (and packages): 5
* `diagram-js`: `1`


I guess we could do two things:

* warn, if we override an existing `type` property
* don't expose the event type via `type` but as something else _?_
