### ISSUE TITLE
Avoid unnecessary firing of views.changed events

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#388]
[Whenever an element of the type `dmn:Definitions` or `dmn:Decision` has changed a `views.changed` event is fired](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-shared/src/base/EditingManager.js#L29) regardless of wether there is an actual change of the views.

There are two cases where there's really a change:

1. The number of elements that can be viewed (`dmn:Definitions` or `dmn:Decision`) has changed.
2. The name of an element has changed.

We should not fire a `views.changed` event in any other case.

Related to https://github.com/camunda/camunda-modeler/issues/1100.
Related to https://github.com/camunda/camunda-modeler/issues/1115

**Comment by philippfromme** [comment]
Will be fixed as part of https://github.com/camunda/camunda-modeler/pull/1811.

**Comment by nikku** [comment]
How will it be fixed as part of a downstream issue?

**Comment by philippfromme** [comment]
Actually this is a slightly different issue than the one that I was working on. Sorry.
