### ISSUE TITLE
Release dmn-js v0.5.0

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#39]

**Comment by gimbel** [comment]
we also changed the code of table-js, maybe that has to be released too

**Comment by meyerdan** [comment]
yes, both projects need to be released. I will talk to @SebastianStamm  :)

**Comment by SebastianStamm** [comment]
* [ ] Release the dmn libraries in order
  * [ ] dmn-moddle
  * [ ] table-js
  * [ ] dmn-js

* [ ] Release the `bower-dmn-js` packaging
  * [ ] check if bundle can be used (`test/app/index.html` opens in browser)

* [ ] Update the examples `dmn-js-examples`
  * [ ] bump used dmn-js version
  * [ ] perform clean/install and test
  * [ ] update screenshots in Github

* [ ] Release `bpmn-io-demo`

* [ ] Write blog post

* [ ] Spread the word
