### ISSUE TITLE
Connection lost on ID change

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#397]
__Steps to Reproduce__

1. Connect a text annotation to a decision in DRD view
2. Go to decision table view and change decision ID
3. Go back to DRD view

__Expected Behavior__

Connection is still there.

__Actual Behavior__

Connection is gone.

![connection-compressed](https://user-images.githubusercontent.com/7633572/54540880-11dc8780-4999-11e9-883c-192014353279.gif)

**Comment by nikku** [comment]
Still an issue in `dmn-js@8`.
