### ISSUE TITLE
Question: advanced mode for DMN

### ISSUE THREAD

**Issue by jeniamoroz** [bpmn-io/dmn-js#399]
In versions of DMN 0.x.x (maybe in 4.x.x and 5.x.x too, but can't remember), it was possible to enter "Advanced Mode" via respective button on the right.
Now that I'm using version 6.x.x, I can't locate such button, neither can trigger it in the code.
My question is, how can I enable Advanced mode for DMN? More importantly, how to enable it by default?
Thanks

**Comment by philippfromme** [comment]
As of version 2.x.x we've abandoned the concept of having two different modes. All of the features are available at any time now.

**Comment by CarstenWickner** [comment]
Hi @philippfromme,
having just a single mode is definitely better.
But how can we enable showing the business-friendly column label at the same time as the (e.g. FEEL) input expression? It seems like you can only see the input expression if the label is left empty.

**Comment by philippfromme** [comment]
@CarstenWickner That's correct.
