### ISSUE TITLE
I can create and read descriptions for cells

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#40]
* add ability to create a description attribute of DMN
* align display of description with hide/show details mode

**Comment by ricardomatias** [comment]
If I add a description in simple-mode, when I switch to advanced mode the styles are broken.

**Comment by SebastianStamm** [comment]
Could you add a more detailed description how to reproduce it or attach a screenshot? I have trouble reproducing it.

**Comment by ricardomatias** [comment]
It happens when the table is too large and the column minimum with logic is activated.

![img-2016-08-04-172649](https://cloud.githubusercontent.com/assets/8850708/17407728/b0d7d362-5a68-11e6-9c49-c4b8a9620786.png)
