### ISSUE TITLE
Upgrade to diagram-js@4

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#400]
Investigate if we can upgrade to diagram-js@4 to inherit some of the features shipped with the latest release.

* [x] Checkout and test current `dmn-js` with diagram-js upgrade
* [x] Bump to diagram-js@4

**Comment by nikku** [comment]
We got to improve the layouter to handle connections without source and target (cf. diagram-js release notes and changes in bpmn-js).

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/402.
