### ISSUE TITLE
decision table in disabled mode

### ISSUE THREAD

**Issue by dhrn** [bpmn-io/dmn-js#401]
__Is your feature request related to a problem? Please describe.__

I want to render the dmn decision table in read-only mode .ie showing in the disabled mode

__Describe the solution you'd like__

I am having a scenario like showing dmn decision table the read, write mode.

**Comment by nikku** [comment]
You may use the viewer distribution to render the table read-only, [cf. example](https://github.com/bpmn-io/dmn-js-examples/blob/master/starter/viewer.html).

**Comment by dhrn** [comment]
we have docs for this?

**Comment by dhrn** [comment]
thanks @nikku

**Comment by dhrn** [comment]
hey @nikku what is the difference between **viewer distribution and modeler distribution**?
