### ISSUE TITLE
Default input expression language in header should not be FEEL

### ISSUE THREAD

**Issue by CarstenWickner** [bpmn-io/dmn-js#405]
__Is your feature request related to a problem? Please describe.__

By default, the input expression language in an input column header is "FEEL".
- As far as I understand, FEEL is meant to be used in input entries (i.e. table cells not table headers) for range and equality checks.
- In the DMN Engine, the default for input columns and output entries is/was JUEL. Only Input entries use FEEL by default.
- In older versions of dmn.js (some time ago) the default here was JUEL, which seems more meaningful.

<img width="576" alt="Bildschirmfoto 2019-10-17 um 13 14 40" src="https://user-images.githubusercontent.com/9433996/67004249-2bd17a80-f0e0-11e9-8d44-9c164139f04e.png">

<img width="522" alt="Bildschirmfoto 2019-10-17 um 13 19 43" src="https://user-images.githubusercontent.com/9433996/67004542-d5187080-f0e0-11e9-9990-ef41b013089f.png">

__Describe the solution you'd like__

The DMN Modeler's default input expression language (in input column headers) should match with the respective default in the DMN Engine.
Making this configurable (as per #19) is one option (especially since this is configurable on the DMN Engine). Changing the current hard-coding from FEEL to JUEL is another.

Change the default expression language for input column headers from _FEEL_ to _JUEL_ (see screenshots above)

* [ ] Change to JUEL in short hint 
* [ ] Set JUEL as the first option in script editor

__Additional Context__

* [Camunda Docs - Default Expression Languages](https://docs.camunda.org/manual/7.11/user-guide/dmn-engine/expressions-and-scripts/#default-expression-languages)

**Comment by pinussilvestrus** [comment]
Hi Carsten!

Thanks for reporting, we will clarify this topic internally and come back to you whether we want to follow it this way in the future. 👍🏻 Stay tuned.

**Comment by pinussilvestrus** [comment]
Hi @CarstenWickner, 

we decided that it absolutely makes sense to align the default expression language with the engine. I'll update the issue description and we will tackle this soon.

**Comment by CarstenWickner** [comment]
Hi @pinussilvestrus,

Is there anything I can do to help? I started to make this all configurable (as per #19) to match the flexibility offered in the DMN Engine, but I'm struggling with your injection system. I don't know where to put the extra props so they would be passed through to where I need them, e.g. in the `features/decision-table-head` and `features/expression-language`.

Can you maybe give me some pointer for that pass-through of props?
I'd be happy to provide a PR as basis for further discussions/decisions on your end then.

**Comment by pinussilvestrus** [comment]
Feel free to open a pull-request with the changes you already made and we can have a look at it / providing some help for open problems.
