### ISSUE TITLE
Show both Label AND variable name for outputs

### ISSUE THREAD

**Issue by renepeinl** [bpmn-io/dmn-js#408]
Context
For the input variables, the system distinguishes between input label (human readable) and input variable (id that has to match with process variables). Both are shown in the colum header with the variable name being shown inverted as white text on grey background. This is nice for the human reader, especially for a domain expert and IT expert doing the modelling together.

Problem
For the output variable, this distinction is helpful as well. The editor already shows output label and output name and my assumption is that one is the human readable text and the other is the internal id. However, in contrast to input variables, only the label is displayed in the output column header.

Suggested solution
Please show both output label and output name in the same manner as for input variables.

**Comment by pinussilvestrus** [comment]
Thanks for your request! We will have to discuss it internally and then decide whether we want to have this implemented. Stay tuned 🔊!

**Comment by MaxTru** [comment]
How output name and label are displayed was changed with dmn-js@9.0.0. Could you please have a look at the new layout (e.g., by [downloading a Camunda Modeler v4.x.x ](https://camunda.com/download/modeler/))? If the issue still remains from your perspective, please reopen this. Based on feedback we will re-evaluate and potentially adjust the layout. Thanks
