### ISSUE TITLE
DMN 1.3 support

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#409]
This issue tracks our progress towards DMN 1.3 support.

* We can read DMN 1.3 XML (https://github.com/bpmn-io/dmn-moddle/issues/3)
* A utility allows us to migrate DMN 1.1 to DMN 1.3 (https://github.com/bpmn-io/dmn-js/issues/410)
* We use DMN 1.3 DI for graphical information in DRDs
  * [x] Migrate [`DiGenerator`](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-drd/src/features/generate-di/DiGenerator.js)

CamBPMN Issue: https://app.camunda.com/jira/browse/CAM-10919

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/452

**Comment by nikku** [comment]
Does it make sense to publish a [blog post](https://bpmn.io/blog) and [create an example for this](https://github.com/bpmn-io/dmn-js-examples).

I guess it could be helpful for both internal and external users.

**Comment by nikku** [comment]
Or maybe wait until DMN 1.3 is officially ratified? DMN 1.2 is [still the latest version](https://www.omg.org/spec/DMN/About-DMN/).

**Comment by philippfromme** [comment]
I've already started creating an example. For the blog post, I'd wait for a stable release after DMN 1.3 has officially been released.

**Comment by barmac** [comment]
Cf. https://github.com/bpmn-io/dmn-js/issues/456

**Comment by nikku** [comment]
We could prepare the post, if we have time to do so.
