### ISSUE TITLE
When typing new line in the cell, cursor jumps back

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/dmn-js#41]
See [original post](https://forum.bpmn.io/t/strange-behavior-after-entering-a-newline-in-a-cell-of-the-dmn-decision-table-editor/730) for details.

![dmn](https://cloud.githubusercontent.com/assets/2331533/15530876/4ac70eba-2257-11e6-9686-f93fb23170a9.gif)

**Comment by nikku** [comment]
Should be addressed via #297.
