### ISSUE TITLE
Create a DMN 1.1 to DMN 1.3 migration utility

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#410]
#### What to Migrate

* [x] Migrate namespace
* [x] Migrate our custom DI, used in DRDs to DMNDI
* [x] Other things (__please investigate__)

#### Alternatives

We find an existing JavaScript based migration utility that does the job.

---

Child of https://github.com/bpmn-io/dmn-js/issues/409

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/dmn-migrate
