### ISSUE TITLE
Table Row Height Breaks in Chrome 78

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#417]
Height of table rows breaks due to fixed width of first column (`40px`). Used to work in Chrome <78, breaks in Chrome 78.

![dmn-layout](https://user-images.githubusercontent.com/7633572/67659524-d6596100-f95c-11e9-86b9-53fa3dc49ad2.gif)

**Comment by barmac** [comment]
This is a Chrome bug which is already fixed in `78.0.3904.87`.

Cf. https://support.google.com/chrome/thread/17644323?hl=en
