### ISSUE TITLE
Dropdown options in a context menu cannot be selected anymore

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js#421]
__Describe the Bug__

After update to `table-js@6.0.1`, it occurred that the options in `InputSelect` can't be selected anymore if the component is placed in a context. I'm sure this is because the dropdown options are rendered outside of the context menu which causes the menu to close on global mousedown.

__Steps to Reproduce__

1. Open the dropdown
2. Try to select any option

__Expected Behavior__

It should work.

__Environment__

Please complete the following information:

 - Browser: Chrome 78
 - OS: MacOS
 - Library version: `develop` with updated `table-js`

**Comment by DenysVuika** [comment]
This issue still happens with dmn-js 10.0.0, when using decision table editor... the hit policy editor does not react on mouse clicks (however works with the keyboard). Should I raise a new bug for that?

**Comment by nikku** [comment]
Please open another bug, provide concrete steps to reproduce and/or a screen cast.

**Comment by barmac** [comment]
Can you reproduce that on the [demo website](https://demo.bpmn.io/dmn/s/check-order)? On my machine (Chrome 87 / MacOS) it works correctly.

**Comment by DenysVuika** [comment]
@barmac I've created an issue: https://github.com/bpmn-io/dmn-js/issues/615

**Comment by barmac** [comment]
Thank you.
