### ISSUE TITLE
Clearing Predefined Values Navigates

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#431]
![dmn-js-anchor](https://user-images.githubusercontent.com/7633572/68112037-bee81e00-fef0-11e9-8f7e-7fc4390d4cc3.gif)

__Describe the Bug__

Clicking the `<a>` tag to clear predefined values navigates to `#`. This doesn't happen in the Camunda Modeler but it happens on [demo.bpmn.io/dmn](demo.bpmn.io/dmn).

__Steps to Reproduce__

1. Open decision table
2. Clear predefined values

__Expected Behavior__

No navigation.

**Comment by barmac** [comment]
I'm wondering why it is a link in the first place...

**Comment by philippfromme** [comment]
> I'm wondering why it is a link in the first place...

Good question.

**Comment by barmac** [comment]
Also, this is not the only place where the `<a href="#" />` is used as a button.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/432
