### ISSUE TITLE
Integrate Code Coverage 

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#442]
In the past, looking at code coverage as a quality gate helped us to find some good bugs / missing tests across our tool landscape (Camunda Modeler, diagram-js, bpmn-js, ...). I presume it will help us to raise the quality in the DMN feature department, too.

I propose that we enable code coverage reporting for this library and integrate it into our CI pipeline.

**Comment by barmac** [comment]
Makes sense. I'm gonna look into that.
