### ISSUE TITLE
Knowledge source not visible

### ISSUE THREAD

**Issue by micheldebree** [bpmn-io/dmn-js#448]
__Describe the Bug__

Knowledge sources in a DMN are not shown.

__Steps to Reproduce__

1. Visualize the [attached DMN](https://github.com/bpmn-io/dmn-js/files/3973631/Conclusienl.imow-mn002.activiteit.Rijksmonumentenactiviteit.xml.zip) with dmn-js

__Expected Behavior__

See nodes for the knowledge sources

__Environment__

Please complete the following information:

 - Browser: Firefox 71.0
 - OS: macOS 10.14.6
 - Library version: 7.2.1

**Comment by nikku** [comment]
The diagram does not contain any graphical information. This is why we auto generate certain pieces of graphical information for you to see something when you visualize the DRD. 

As part of https://github.com/bpmn-io/dmn-js/issues/411 we plan to upgrade to DMN 1.3 that supports graphical information. Maybe the tool you used allows you to export the diagram as DMN 1.3 with graphical information?

**Comment by micheldebree** [comment]
Thanks for the quick reply. We do indeed enrich the DMN with graphical information before it is sent to `dmn-js`. I delved a bit deeper into the code (that I inherited) and realize most of the things we see now are explicitly added to the DMN xml for visualization. This is what part of our diagram looks like (without the red notes I added):

<img width="950" alt="Screenshot 2019-12-18 at 06 32 06" src="https://user-images.githubusercontent.com/4125356/71061415-394ec380-2168-11ea-9b17-5b7a14dce74c.png">

It seems we need to put some extra code in to add visualization for knowledge sources. I am still a bit unclear on what DMN elements get rendered 'out-of-the-box' though. If I open the source DMN (not enriched with visualization) on the demo site, I only see the `decision` elements and not the `inputData` elements, although we don't seem to be doing anything to visualize them in the final DMN. Do only the `decision` elements get rendered out-of-the-box?

**Comment by nikku** [comment]
> Do only the decision elements get rendered out-of-the-box?

No. We generate basic graphical information once you switch to a DRD without grapical information attached (cf. [`DiGenerator`](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-drd/src/features/generate-di/DiGenerator.js)). This however does only include decisions, nothing else.

I'm closing this issue, as there is nothing we are going to do about this for now.
