### ISSUE TITLE
Blog post about DMN 1.3 support

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#458]
__What should we do?__

Introduce next major version of dmn-js and announce DMN 1.3 support.

Give users an introduction into how to migrate diagrams and/or user our new tooling on DMN 1.1 files.

Optional: Link to official example (consume dmn-11 or something).

__Why should we do it?__

All users using dmn-js will have that issue and it is good to have an official communication regarding this.

**Comment by pinussilvestrus** [comment]
Along with this it would make sense to [update the dmn-js-examples](https://github.com/bpmn-io/dmn-js-examples/issues/10)
