### ISSUE TITLE
Publish example that shows how to consume DMN 1.1 and DMN 1.2 files

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#464]
__What should we do?__

An example should clearly demonstrate how to consume DMN 1.1 and DMN 1.2 files with the tool.

That example should be published in our [examples repository](https://github.com/bpmn-io/dmn-js-examples).

__Why should we do it?__

Because people need to learn about how to transition between dmn-js 7.x and dmn-js 8.0.

**Comment by philippfromme** [comment]
Example: https://github.com/philippfromme/dmn-js-dmn-1-3-example

**Comment by nikku** [comment]
Must be made official / linked to official sources.

Also we should consider renaming it to dmn-js-migration or something, as it should showcase the general way to migrate.

**Comment by philippfromme** [comment]
Yes, the intention is to add it to the dmn-js-examples repository.
