### ISSUE TITLE
Spike: There is a way to highlight FEEL syntax in expressions

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js#469]
__What should we do?__

Check whether it is feasible to use a [FEEL parser](https://github.com/nikku/feelin) to highlight FEEL syntax in:
1) Decision table
2) Literal expression view

__Why should we do it?__

This will make writing expressions easier and more productive.

**Comment by pinussilvestrus** [comment]
We have this / a similar topic on our [Hypothesis Board](https://docs.google.com/spreadsheets/d/1ZI1GDUHJFP_RWLeIKFFxzFAlyJzH4Ozt2ApZnHIhVqQ/edit?usp=sharing) as well

> DMN tables that allow only for FEEL expressions are still flexible enough (assuming more complex literal expressions are used)

Any input after you did your spike is appreciated :-o)

**Comment by barmac** [comment]
Work is happening in https://github.com/barmac/dmn-js-syntax-highlighting

**Comment by barmac** [comment]
I documented the findings here: https://docs.google.com/document/d/1JFj97E5TmA-oheYplPJQUtid4hvFEwCNYfQLSTGWcJQ/edit?usp=sharing
