### ISSUE TITLE
Display orthogonal arrowheads on top-down DRDs

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#479]
__Is your feature request related to a problem? Please describe.__

During our user studies we found out, following DRD layout fits the best for a good understandability of the decision requirements logic.

![image](https://user-images.githubusercontent.com/9433996/75226138-2382fd80-57ac-11ea-9f41-2b2519f3b602.png)

#470 deals with overall top-down modeling improvements. Another thing we should investigate are the orthogonal arrowheads.

Note that the incoming docking points are also aligned (defined distance, ordering depends on the ordering of the next level elements).

__Describe the solution you'd like__

* Decision input connections are always shown with bent as shown below:

    ![image](https://user-images.githubusercontent.com/9433996/75226197-48777080-57ac-11ea-85d8-da255c7e86ab.png)

* Incoming connections are laid out / centered automatically based on the amount of connected elements:

![image](https://user-images.githubusercontent.com/58601/75249696-0a437680-57d7-11ea-971f-005309df6477.png)

![image](https://user-images.githubusercontent.com/58601/75249364-783b6e00-57d6-11ea-9050-779fbeea3b99.png)

![image](https://user-images.githubusercontent.com/58601/75251818-a7a0a980-57db-11ea-9b55-b265ac37c423.png)

In future iteration we may improve on the layouting capabilities.

__Describe alternatives you've considered__

/

**Comment by philippfromme** [comment]
Is this up for discussion or have we decided that we're going for it?

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/492
