### ISSUE TITLE
Implement new Context Menu Layout on Column Headers

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#495]
__What should we do?__

Implement the new design of the context menu when right-clicking on a column header

![image](https://user-images.githubusercontent.com/9433996/79536793-26e68700-8081-11ea-8d24-c63079361598.png)

* [ ] Design is adapted
* [ ] Order of items is changed
* [ ] New <Edit Column> action is added

Another thing we could consider: State out the type of the column inside the menu, e.g. "Edit Input Column"

__Why should we do it?__

It aligns better to the new decision table layout.

Child of #494 

Related to https://github.com/bpmn-io/dmn-js/issues/501

**Comment by barmac** [comment]
Do we want to change the cell context menu look too? It seems to make use of the same component with some additions.

![image](https://user-images.githubusercontent.com/28307541/80584748-6d899900-8a12-11ea-9fc4-e922307c1696.png)

**Comment by pinussilvestrus** [comment]
Potentially yes, but this issue is only related to the table headers. We did not make a final decision on the rule cells for now

**Comment by barmac** [comment]
Actually, to implement the new context menu action I first need to have [this](https://github.com/bpmn-io/dmn-js/issues/501) done.

**Comment by barmac** [comment]
I'll first try out with input/output related context menu to be removed from the rule context menu.

**Comment by barmac** [comment]
So that's how it looks on my branch:

![image](https://user-images.githubusercontent.com/28307541/82898665-fc2dff00-9f59-11ea-8c27-f2b0f130daa1.png)

![image](https://user-images.githubusercontent.com/28307541/82898655-f801e180-9f59-11ea-93b7-c05289aa7946.png)

There is a problem of missing column-related context menu. As discussed, it might make sense to tackle both context menus at once. Otherwise, we have to add some code which will soon have to be removed again.

**Comment by barmac** [comment]
This is how it looks like on Google Docs:

![image](https://user-images.githubusercontent.com/28307541/83022104-50ed7a80-a02b-11ea-9bcc-32c03ac55b58.png)

What I can see is that the actions are grouped by the action type ("delete", "insert"). Then there is differentation: columns, rows. I want to try out how it would look like in the DMN context.

**Comment by pinussilvestrus** [comment]
I also see having everything in one column would be more natural for a context menu. I think it's worth it trying it out

**Comment by barmac** [comment]
One column, icons removed:

![image](https://user-images.githubusercontent.com/28307541/83124712-d7ab6180-a0d6-11ea-8028-799d7592197c.png)

**Comment by barmac** [comment]
Not sure if we need each direction for column/row paste actions.

Also, please note that description and script language entries are missing.

**Comment by barmac** [comment]
Or even:

![image](https://user-images.githubusercontent.com/28307541/83125711-2ad1e400-a0d8-11ea-93af-615a67eaba72.png)

**Comment by pinussilvestrus** [comment]
I like the idea of having sections separated action-wise. It only confused me a bit that rules and columns are no in the same area, but this might only come from the fact it was different before.

Basically it feels a bit more "context-menu-native" to me now 👍  The question is, where would the cell menu now been placed?

**Comment by nikku** [comment]
Change expression and and description should refer to the actual _cell_ being targeted here.

**Comment by philippfromme** [comment]
> You can always use drag'n'drop feature to move them to the top/left if you really need.

This is only try if you only have a few columns that fit on your screen.

**Comment by philippfromme** [comment]
Seperating copy cut and paste leads to too many seperators. I wouldn't do that.

**Comment by barmac** [comment]
![image](https://user-images.githubusercontent.com/28307541/83134779-219b4400-a0e5-11ea-8b0b-02133caabe3b.png)

How about this?

**Comment by philippfromme** [comment]
_Insert Rule_ sounds like inserting an existing rule. I'd stick with _add_ and _remove_ or go with _insert_ and _delete_ like Google Sheets calls it.

**Comment by barmac** [comment]
I'll keep it as _add_ and _remove_ for now.

**Comment by barmac** [comment]
I still need to figure out what to do with the expression language, but this is how it looks right now:

![context-menu](https://user-images.githubusercontent.com/28307541/83257846-7d350280-a1b5-11ea-9070-30cc836212b5.gif)

**Comment by philippfromme** [comment]
We could have a multi-level context menu like this:

![image](https://user-images.githubusercontent.com/7633572/83258254-3c89b900-a1b6-11ea-9f17-ce849ed355e0.png)

**Comment by barmac** [comment]
Do we actually support multi-level context menu in `table-js`?

**Comment by philippfromme** [comment]
Not yet. 😎
