### ISSUE TITLE
Remove decision id component from decision table

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#496]
__What should we do?__

Remove the ability to show and edit the decision id in a decision table.

__Why should we do it?__

We decided to not have this one inside the new decision table layout

![image](https://user-images.githubusercontent.com/9433996/79537059-bee47080-8081-11ea-9aeb-2dfed7e262a9.png)

Child of #494

**Comment by pinussilvestrus** [comment]
Should we also include that one into the Camunda Modeler 4.alpha-2 release once merged? @barmac @philippfromme?

**Comment by philippfromme** [comment]
Preferably, yes.
