### ISSUE TITLE
Implement new hit policy design

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#497]
__What should we do?__

Implement new design of the hit policy

![image](https://user-images.githubusercontent.com/9433996/79537183-0965ed00-8082-11ea-81fa-29b8a1218af4.png)

Things we can consider:
* Do we have to show the explanation hint at all (or not all the time)?
* Keep the original hit policy place as an intermediate step? To avoid confusion.

__Why should we do it?__

It helps the (getting started) user to understand the hit policy options more.

Child of #494

**Comment by barmac** [comment]
How would you expect the decision name to behave like? Should it have a maximum width?

![buffalo](https://user-images.githubusercontent.com/28307541/80692290-a9376800-8ad1-11ea-8a8e-486b357002a6.gif)

IMO the behavior from the GIF is OK if we just have an ellipsis for the overflowing content.

**Comment by pinussilvestrus** [comment]
Since we're planning to have a maximum width for the column headers, maybe it makes sense to have this as well for the name property.

I'll reach out to @volkergersabeck to clarify it

**Comment by nikku** [comment]
For a common sense solution I'd argue for a max width decision table name.

It encourages best practices. If you'd write a novel in it, you can always hover the name to see the full text as a title.

**Comment by barmac** [comment]
![image](https://user-images.githubusercontent.com/28307541/80698687-21eef200-8adb-11ea-934a-4a8192dfad68.png)

Like this, right?

**Comment by pinussilvestrus** [comment]
Looks good 👍

**Comment by barmac** [comment]
Regarding explanation, we will start without it.
