### ISSUE TITLE
Implement new ability to create columns to the right

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#498]
__What should we do?__

Implement the new adding-column design

![image](https://user-images.githubusercontent.com/9433996/79537376-72e5fb80-8082-11ea-85d4-c6816aa96159.png)

Note that,
* the adding circles are placed at the end the last input and output column
* centered vertically on the line
* the double border is getting thicker

__Why should we do it?__

We can get rid of the overloading global input/output header

Child of #494

**Comment by barmac** [comment]
Note: the button should be centered vertically.
