### ISSUE TITLE
Implement new column header editing component

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#501]
__What should we do?__

Implement the new editing component for input/output column headers

![image](https://user-images.githubusercontent.com/9433996/79539407-8bf0ab80-8086-11ea-9e05-a5feb1eeb49f.png)

![Kapture 2020-04-17 at 8 35 40](https://user-images.githubusercontent.com/9433996/79539416-90b55f80-8086-11ea-8c2a-c7891a46bb80.gif)

_What we know_
* [x] Only have one editing component for column headers (get rid of type modal)
* [x] Opens when double-clicking the cell
* [x] The input label/output name should be in place editable 
   * closes on \<Enter\>
  * single line only
  * content will NOT be cropped but grows with its content
* [ ] ~~One combined input field for type / allowed values~~
   * ~~offers autosuggestion for primitive datatypes~~
* [x] offers an expression field for input columns
  * single line per default
  * enables multi-line script option via \<Enter\>
  * height fits by its content

*What we don't know currently*
* Indicate column type (input/output) inside the editing component?
* Can we drop the input variable?
  * Background: DMN 1.3 introduces the `?` operator for cell variables. We would need a migration path then.
* If possible: generate expression out of the label, e.g. "Open Claims" -> "openClaims"
* Can we drop the expression language dropdown to choose the type? **Currently Not.**
* Can we drop the output variable?

__Why should we do it?__

We can get rid of having multiple popups open inside the headers.

Child of #494

**Comment by barmac** [comment]
> One combined input field for type / allowed values
> offers autosuggestion for primitive datatypes

I am not sure if we really want this as it would prevent users from modeling inputs like this:

```xml
<input id="_dc6c54d5-80a0-4b78-aa83-0a33802de55c" label="Age">
    <inputExpression typeRef="number">
        <text>Age</text>
    </inputExpression>
    <inputValues>
        <text>[18..120]</text>
    </inputValues>
</input>
```

I'd rather allow to provide `inputValues` for all types instead of having this as a string-only feature.

**Comment by barmac** [comment]
Still, DMN Engine handles values outside of `inputValues`:

![image](https://user-images.githubusercontent.com/28307541/84485867-df553380-ac9c-11ea-9061-cf3836963353.png)

**Comment by barmac** [comment]
I just had a look at how [Signavio](https://www.signavio.com/) handles Input Values. They don't allow me to type custom value in Input Entries. I think it is the right approach as 

It's also interesting how the expression can be generated via UI input. I cannot manually type FEEL expression for the input values though.

![signavio](https://user-images.githubusercontent.com/28307541/84490503-8e950900-aca3-11ea-863e-e1fdae82d55b.gif)

**Comment by barmac** [comment]
>  One combined input field for type / allowed values
> offers autosuggestion for primitive datatypes

As discussed, we are not implementing this yet.
