### ISSUE TITLE
Switch from callback to promises

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#514]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

The core public APIs for dmn-js shall be migrated from Callbacks to Promises. This affects:

**Public APIs**
- [x] `DmnModdle#fromXML` (https://github.com/bpmn-io/dmn-moddle/issues/19)
- [x] `DmnModdle#toXML` (https://github.com/bpmn-io/dmn-moddle/issues/19)
- [x] `Manager#importXML`
- [x] `Manager#saveXML`
- [x] `Viewer#saveSVG`

**Internal APIs (e.g., communication between `Manager`, `table`, ...)**
- [x] `Manager#open` and `Viewer#open` (https://github.com/bpmn-io/dmn-js/pull/636)

Note: this leads to not supporting IE11 anymore, one would need to polyfill promises in this case.

Doing this shall follow the same approach as the [bpmn-js promisifaction in early 2020](https://github.com/bpmn-io/bpmn-js/issues/812). This approach set the following cornerstones:

* Don't use a wrapper but modify each API (e.g., public API shall inherently return a promise, the private API may still be callback-based). (See [RfC](https://github.com/bpmn-io/rfcs/tree/master/001-callbacks-to-async-apis))
* Ship major releases once this was implemented (for `DmnModdle` as well as for `dmn-js`)
* If a user still passes callbacks to dmn-js, then issue an error. But don't crash. Show a meaningful error message linking to "how to migrate from callback to promise APIs".
* For DmnModdle => don't offer callback API anymore (same approach as for BpmnModdle)

In particular we need to:

- [ ] Implement and release the change
- [ ] Update the documentation (incl. examples in other repos)
- [ ] Create a blog post for the major release (new deep link / or update the old article to also be meaningful for dmn-js)

__Why should we do it?__

* We should provide consistent developer experience across our libraries. 
* Promises nicely integrate with `async`/`await`

__Context__
[bpmn-js RfC](https://github.com/bpmn-io/rfcs/tree/master/001-callbacks-to-async-apis)
[bpmn-js promisifaction in early 2020](https://github.com/bpmn-io/bpmn-js/issues/812)

**Comment by MaxTru** [comment]
Closed with https://github.com/bpmn-io/dmn-js/issues/641

**Comment by nikku** [comment]
Do we plan to follow up with updates to our examples and a potential blog post?

**Comment by MaxTru** [comment]
Yes will release today and then follow up (cf. https://github.com/bpmn-io/dmn-js-examples/issues/21)
