### ISSUE TITLE
Fill expression language field with FEEL per default

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js#527]
__Is your feature request related to a problem? Please describe.__

> I’d love if we set FEEL as the default expression language so that the user does not need to select a value here.

This would make it clear what expression language is the default.

__Describe the solution you'd like__

Fill expression language field with FEEL per default.

__Describe alternatives you've considered__

Leave it as it is.

**Comment by philippfromme** [comment]
Where does that quote come from?

**Comment by barmac** [comment]
> Where does that quote come from?

Camunda Slack.
