### ISSUE TITLE
Simple Mode Button Position Not Updated

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#543]
__Describe the Bug__

When changing the cell position (e.g. by adding a column) the simple mode button's position isn't updated.

![09-07-_2020_12-00-20](https://user-images.githubusercontent.com/7633572/87026301-d6904880-c1db-11ea-9018-5a0be30e51be.gif)

__Steps to Reproduce__

1. Click a cell to open the simple mode button
2. Change the cell position by adding a column

__Expected Behavior__

The simple mode button position is updated.

__Environment__

 - Library version: 8

---

Related to https://github.com/bpmn-io/dmn-js/pull/530

**Comment by snehal199** [comment]
Can I pick this up @philippfromme ?

**Comment by avats-dev** [comment]
@philippfromme can you guide me how to resolve this? I want to contribute, thanks.

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/dmn-js/pull/654.
