### ISSUE TITLE
Label Edit Mode in DRDs is broken if the user directly opens a table

### ISSUE THREAD

**Issue by volkergersabeck** [bpmn-io/dmn-js#547]
__Steps to Reproduce__

1. Open a DRD
2. start editing one element's label by double clicking the element and typing text
3. click on the green icon of another decision table to switch to the table editing view
4. click on "Edit DRD" and return to the DRD view
5. the first element is still in edit mode with the typed text visible
6. clicking on the background to confirm the label closes the edit mode, but the new text is not applied

![DRD label editing](https://user-images.githubusercontent.com/232571/88155037-d9416380-cc07-11ea-92b5-d5be2a5cbf82.gif)

__Expected Behavior__

When opening a decision table, any pending edit more is closed by confirming the text change.
When returning to the DRD, there is no element still in edit mode

**Comment by MaxTru** [comment]
Reproduced using dmn-js@8.3 and and dmn-js@9.0

**Comment by MaxTru** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/548
