### ISSUE TITLE
Output name must not contain white spaces

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#551]
__Is your feature request related to a problem? Please describe.__

Having a whitespace in an output name will lead to an error in the decision table execution.

__Describe the solution you'd like__

Add a validation to the output name field and check for whitespaces. Output name must not contain whitespaces.

__Describe alternatives you've considered__

n/a

__Additional context__
![Screenshot_20200729_112954](https://user-images.githubusercontent.com/42800119/88783264-d8bc4600-d18e-11ea-81c7-e5adc0572099.png)

**Comment by sanskar-p** [comment]
@MaxTru, can you please tell me exactly which component/file name I have to add the validation to? I'm new to this project and unfamiliar with the codebase.

**Comment by MaxTru** [comment]
Dear @sanskar-p . This is a great issue to start contributing to bpmn-io libraries. The component you are looking for is this one: https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputEditor.js#L61.

**Comment by sanskar-p** [comment]
@MaxTru, thanks! I'll start working on it right away.

**Comment by sanskar-p** [comment]
Hi. I can't seem to figure out how to run the project locally. Can you please advise on that. Also, I'm having trouble implementing the validation. Can you give some tips on that? I am a beginner at this. Sorry for the inconvenience.

**Comment by MaxTru** [comment]
Have you been trying to follow this guideline: https://github.com/bpmn-io/dmn-js#Building-the-Project

When running this, you should be able to open http://localhost:9876/debug.html to see the result of some text cases. This you can use as starting point to test your changes.

**Comment by adithyaakrishna** [comment]
Hey @MaxTru Can I work on this issue?

**Comment by MxCvlibr** [comment]
@MaxTru  I can run the debug page locally but how do I open the page of the output, the one you showed in the picture above?

**Comment by MaxTru** [comment]
See conversation in https://github.com/bpmn-io/dmn-js/pull/666

This could potentially be tackled with engine-specifc linting (one day maybe)

**Comment by barmac** [comment]
As a side note, the `dmn-scala` engine can handle output names with spaces correctly.

I tested the diagram below with [the standalone REST engine](https://github.com/camunda-community-hub/dmn-scala/tree/master/engine-rest#how-to-use-it) and it worked just fine.

<details><summary>diagram_1.dmn</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="Definitions_1bmw08j" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" exporter="Camunda Modeler" exporterVersion="4.11.1">
  <decision id="Decision_05ewrd5" name="Decision 1">
    <decisionTable id="DecisionTable_08jst05">
      <input id="Input_1">
        <inputExpression id="InputExpression_1" typeRef="string">
          <text>input</text>
        </inputExpression>
      </input>
      <output id="Output_1" name="my name one" typeRef="string" />
      <output id="OutputClause_0ns10sm" name="my name two" typeRef="string" />
      <rule id="DecisionRule_112idi6">
        <inputEntry id="UnaryTests_08nhfs0">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_0adfzid">
          <text>"one"</text>
        </outputEntry>
        <outputEntry id="LiteralExpression_16k0l9g">
          <text>"two"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram>
      <dmndi:DMNShape dmnElementRef="Decision_05ewrd5">
        <dc:Bounds height="80" width="180" x="160" y="100" />
      </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</definitions>
```
</details>

```sh
curl -XPOST -H 'Content-Type: application/json' -d'{"input":"elo"}' localhost:8080/decisions/Decision_05ewrd5/eval

{"result":{"my name one":"one","my name two":"two"}}
```
