### ISSUE TITLE
Improve first intuition of understanding the decision table by layout by adding default names

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#552]
__Is your feature request related to a problem? Please describe.__

![Screenshot_20200729_113508](https://user-images.githubusercontent.com/42800119/88783813-8f202b00-d18f-11ea-90cd-60cc2cfc1afa.png)
Some new users expressed that they had difficulties of clearly understanding where are outputs and where are inputs based on the decision table layout. 
They expressed two reasons:
* The `When` and `Then` are rather small and not spotted quickly
* The `+` signs give the intuition that they connect the columns using a boolean AND logic (which contradicts the input and output column concept"

__Describe the solution you'd like__

A fist approach to resolve the issue is:
- [ ] Prefill the columns with `Input1` and `Output1`
![Screenshot_20200729_113353](https://user-images.githubusercontent.com/42800119/88783681-6435d700-d18f-11ea-97ce-079f74521f97.png)
- [ ] ~~Move the `+` symbols a bit to the left and top~~

__Describe alternatives you've considered__

n/a

__Additional context__

Collected during DMN training

**Comment by barmac** [comment]
> Move the `+` symbols a bit to the left and top

Where exactly would you expect it? 

![image](https://user-images.githubusercontent.com/28307541/89396913-75429300-d70f-11ea-999f-a15083a126c7.png)

I don't really like the look of this. How about if we show the control on hover only? I'd expect it to be less bold then.

Also, we already use hover effect and title for the button.

<img width="861" alt="Screenshot 2020-08-05 at 11 31 50" src="https://user-images.githubusercontent.com/28307541/89397006-960ae880-d70f-11ea-91de-dbdf0399024f.png">

**Comment by volkergersabeck** [comment]
Could we maybe split this issue in two individual ones?
I'd assume that the default input and output labels is something that we could very easily do and could move the discussion around the "Add Input" buttons to a different issue.

**Comment by MaxTru** [comment]
Okay. Let's not tackle the moving of the "+" buttons as part of this issue since we don't have an obvious solution and don't invest it this at the moment.

**Comment by barmac** [comment]
Do we want to prefill just the names of the first columns in each category (input, output) or prefill all new columns so that it's Input2, Input3... ?

**Comment by andreasgeier** [comment]
I would recommend the latter

**Comment by barmac** [comment]
And then, should it be a placeholder in case of missing both label and expression or rather a real label saved to the XML?

**Comment by barmac** [comment]
Solution sketch: 
![image](https://user-images.githubusercontent.com/28307541/94127326-1240c300-fe59-11ea-9100-e3421980799b.png)
