### ISSUE TITLE
Center the resize hitbox

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#554]
__Is your feature request related to a problem? Please describe.__

Currently the resize hitbox in DMN tables is left from the respective line:
![Bug5](https://user-images.githubusercontent.com/42800119/88785188-2cc82a00-d191-11ea-9d8c-7e5a6e2cdc2f.gif)

__Describe the solution you'd like__

Move the hitbox a bit to right left, so that covers the line itself and a bit space to the right without overlapping the `Then` or `And`

__Describe alternatives you've considered__

n/a

__Additional context__

Discovered during DMN user training

**Comment by barmac** [comment]
I am aiming at this result:
![image](https://user-images.githubusercontent.com/28307541/89034398-24aaee80-d339-11ea-877c-91c5d4a861c6.png)
