### ISSUE TITLE
Be able to remove row when clicking on leftmost column

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#555]
__Is your feature request related to a problem? Please describe.__

DMN decision table columns can be removed by right-clicking in the column header.
The same is not possible for rows. They can only be removed by clicking into a respective cell. 

__Describe the solution you'd like__

The experience should be consistent for rows and colums.

- [ ] Be able to remove a row via context-menu which is opened via right-clicking into the leftmost column.
- [ ] Be able to remove a column via context-menu which is opened via right-clicking into a cell.

__Describe alternatives you've considered__

Alternatively we could only allow adding / removing rows and columns via the leftmost and top row.

__Additional context__

Enhancement collected during DMN user training.

**Comment by barmac** [comment]
I've researched this today and it won't be easy to add context menu support for the indices. The context menu logic for rules is contained within `InteractionEvents` in `table-js`. Since we don't provide `data-element-id` property for index cells, the mentioned component fails to find closest cell.

**Comment by barmac** [comment]
So this is how it's gonna look like:

<img width="1217" alt="Screenshot 2020-08-06 at 12 16 42" src="https://user-images.githubusercontent.com/28307541/89520837-c1103d80-d7de-11ea-9e42-fa00ee97d9ee.png">
