### ISSUE TITLE
Create DI extension for dmn-js (Decision Requirement Graphs)

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#56]
**Idea**
- Create `biodi` extension with `http://bpmn.io/schema/dmn/1.1/di` namespace
- Read DI meta data from `biodi:bounds` and `biodi:edge` extension elements

See [`ExampleWithCamundaDI.dmn`](https://github.com/camunda/camunda-dmn-model/blob/master/src/test/resources/org/camunda/bpm/model/dmn/ExampleWithCamundaDI.dmn) for diagram implementing this.

**Comment by SebastianStamm** [comment]
Will be part of the upcoming release
