### ISSUE TITLE
Cell Description Indicator not Shown

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#562]
__Describe the Bug__

When adding a cell description to a cell the indicator is not shown.

![cell-description](https://user-images.githubusercontent.com/7633572/89043028-2cbe5a80-d348-11ea-9f2d-69afae78ccc5.gif)

__Steps to Reproduce__

1. Add cell description to a cell
2. Select another cell

__Expected Behavior__

Cell description indicator is shown.

__Environment__

Please complete the following information:

 - Library version: 9

**Comment by philippfromme** [comment]
It turns out that none of the things that should be shown in a cell are actually in the cell but at the top right corner of the container.

![image](https://user-images.githubusercontent.com/7633572/89044973-0817b200-d34b-11ea-964c-c75f86c4a558.png)

**Comment by barmac** [comment]
Related to https://github.com/bpmn-io/dmn-js/issues/550

**Comment by barmac** [comment]
If we restore `position: relative` on all table cells, we will run again into issue with table bottom border.

Also, the `position: relative` effect on i.a. table cells is undefined according to CSS 2.1 spec 🙈 https://www.w3.org/TR/CSS21/visuren.html#propdef-position

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/566
