### ISSUE TITLE
CSS linting

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/dmn-js#563]
__Is your feature request related to a problem? Please describe.__

We should consider adding CSS linting in our build pipeline. That'd help us avoid possible mistakes such as the one we did in [v9.1.0](https://www.npmjs.com/package/dmn-js/v/9.1.0).

__Describe the solution you'd like__

Add CSS linting as an npm script.

__Describe alternatives you've considered__

None.

**Comment by daniloff200** [comment]
I think, https://stylelint.io/ can be a good solution for that.
Could you assign this issue to me, please, I'm going to add a script

**Comment by oguzeroglu** [comment]
Hey,

Here's [our contribution guidelines](https://github.com/bpmn-io/dmn-js/blob/develop/.github/CONTRIBUTING.md). Feel free to open a PR about this issue. Thanks for your interest!
