### ISSUE TITLE
Remove description if there's only a carriage return 'enter'

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#57]
At the moment, if you had a description with a carriage return it saves it as a description.

Aim: Improve description removal.

Possible scenario: close description box if everything was deleted and an enter is pressed.

**Comment by SebastianStamm** [comment]
At the moment, if you have two carriage returns, or a space or any other whitespace than exactly one carriage return, it is still saved as description.

I think we should do the following: 
1. Only save the description if there is something that is not whitespace (i.e. `value.trim() !== ''`)
2. Close the description popup when ENTER is pressed. Line breaks could be done with Ctrl+Enter (that would also be consistent with how we add line breaks within cells)
