### ISSUE TITLE
The hit policy drop down is rendered at the wrong place

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#589]
__Describe the Bug__

The hit policy drop down is rendered at the wrong place:
![hitPolicyBug](https://user-images.githubusercontent.com/42800119/95348838-b6e1ec80-08be-11eb-9295-338bfffa5e31.gif)

__Steps to Reproduce__

1. Open Decision Table
2. Click on the Hit Policy
3. Will be opened at wrong place

__Expected Behavior__

Hit policy is rendered at right place

__Environment__

Please complete the following information:

- Camunda Modeler 4.3.0-rc0
 - OS: Manjaro Linux
 - Library version: 6.7.1

**Comment by pinussilvestrus** [comment]
I debugged it a bit and discovered this bugs starts with moving the logo, cf. 6836de194f3215d6fdbcbd84bedd92c3be4c9fd5

**Comment by hari-parasuraman** [comment]
Similar issue found when the user tries to edit the input field

<img width="898" alt="Screenshot 2020-10-08 at 10 01 45" src="https://user-images.githubusercontent.com/51324906/95434137-315b4c80-0951-11eb-944e-0d672e42fdc2.png">

**Comment by barmac** [comment]
I just had a call with @pinussilvestrus and we together sketched a solution for the issue. We are going to switch to absolute positioning for the select in a similar manner as we do with the context menus. The fix seems to be feasible to implement well before the Camunda Modeler release.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/dmn-js/commit/318796d95055f9832a97becd4a1a1a80d87a3b39
