### ISSUE TITLE
Color of bpmn-io logo in DRD and Decision Table view differ

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#591]
__Describe the Bug__

Color of bpmn-io logo in DRD and Decision Table view differ.

In DMN Decsion View it is black.
In DRD view it is `#404040`.

__Steps to Reproduce__

1. Compare both logos

__Expected Behavior__

Both logos should be black

__Environment__

`dmn-js v9.3.1`

__Context__
Discovered during regression testing of https://github.com/bpmn-io/dmn-js/issues/589
Introduced with https://github.com/bpmn-io/dmn-js/issues/573

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/599
