### ISSUE TITLE
bpmn-io logo overlay scrollbars

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#592]
__Describe the Bug__

bpmn-io layer overlays scrollbars on many browser environments.

(This of course depends on resolution, ratio and browser)
![image](https://user-images.githubusercontent.com/42800119/95457575-611a4c80-0971-11eb-95b1-c0c9edd6f7eb.png)

__Steps to Reproduce__

1. Have dmn table large enough to show scrollbars
2. See logo overlapping

__Expected Behavior__

* The margin should (maybe) be increased to not overlap the scrollbars in most scenarios
* The scrollbars should overlay the logo (and not vice versa)

__Environment__

`dmn-js v9.3.1`

__Context__
Discovered during regression testing of https://github.com/bpmn-io/dmn-js/issues/589
Introduced with https://github.com/bpmn-io/dmn-js/issues/573

**Comment by MaxTru** [comment]
Quick fix could be the remove the `5px` padding and increase the margin by `5px`

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/593
