### ISSUE TITLE
Create an alpha release with latest inferno@5.6 updates

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#619]
__What should we do?__

We should create an alpha version (`v10.1.0-alpha.0`) with the latest inferno migration updates. 

__Why should we do it?__

We should carefully try out whether the upgrade to a newer inferno version will cause unexpected side effects, especially for extensions.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/dmn-js/commit/23e5552f74f6954e5815c9258a1f0a245175d80d.
