### ISSUE TITLE
saveSVG

### ISSUE THREAD

**Issue by nekdolan** [bpmn-io/dmn-js#627]
__Describe the Bug__

Exporting DMN as SVG does not work.

__Steps to Reproduce__

1. install npm package
2. load production bundle
3. call saveSVG

```
modeler.diamgramViewer.getActiveViewer().saveSVG()
```
dmn-modeler.production.min.js?5bb5:16 Uncaught TypeError: t is not a function
    at vf.ri.saveSVG (dmn-modeler.production.min.js?5bb5:16)
    at VueComponent.eval (diagramMixin.js?5073:84)
    at invokeFunc (lodash.js?2ef0:10359)
    at trailingEdge (lodash.js?2ef0:10408)
    at timerExpired (lodash.js?2ef0:10396)

__Expected Behavior__

Not throw error

__Environment__

Please complete the following information:

 - Browser: Firefox
 - OS: Linux
 - Library version: 10.1.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Are you trying to execute `saveSVG` when the active editor is a Decision Table? This API is currently [only supported for DRD diagrams](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-drd/src/Viewer.js#L96). It simply does not exist for other editors.

Also explorable in this [CodeSandbox](https://codesandbox.io/s/dmn-jssavesvg-u22js).

**Comment by nekdolan** [comment]
I made a mistake by using saveSVG without a callback (with a promise as in BpmnJS). Now it works. Thanks.
