### ISSUE TITLE
Switch from callback to promise based APIs

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#629]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

The core public APIs for dmn-js shall be migrated from Callbacks to Promises. This affects:

* `DmnModdle#fromXML`
* `DmnModdle#toXML`
* `Manager#importXML`
* `Manager#saveXML`
* `Viewer#saveSVG`

Doing this shall follow the same approach as the [bpmn-js promisifaction in early 2020](https://github.com/bpmn-io/bpmn-js/issues/812). This approach set the following cornerstones:

* Don't use a wrapper but modify each API (e.g., public API shall inherently return a promise, the private API may still be callback-based). (See [RfC](https://github.com/bpmn-io/rfcs/tree/master/001-callbacks-to-async-apis))
* Ship major releases once this was implemented (for `DmnModdle` as well as for `dmn-js`)
* If a user still passes callbacks, then issue an error. But don't crash.

In particular we need to:

- [ ] Implement and release the change
- [ ] Update the documentation (incl. examples in other repos)

__Why should we do it?__
We should provide consistent developer experience across our libraries.

__Context__
[bpmn-js RfC](https://github.com/bpmn-io/rfcs/tree/master/001-callbacks-to-async-apis)
[bpmn-js promisifaction in early 2020](https://github.com/bpmn-io/bpmn-js/issues/812)

**Comment by pinussilvestrus** [comment]
Maybe we can close this one then: https://github.com/bpmn-io/dmn-js/issues/514

**Comment by MaxTru** [comment]
Thanks for highlighting, I overlook that one.

Closed as duplicate from #514
