### ISSUE TITLE
Right-click should not focus when clicking the row numbers column

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/dmn-js#63]

**Comment by GitMensch** [comment]
If I understand this correctly the "issue" was that the context menu opened in the numbered column.
Why is this an issue?`

Actually I've tried to find a way to remove/duplicate rules and could not find a way to do this. The reason:

We have the following context menu on an input "column head":
![grafik](https://user-images.githubusercontent.com/6699539/29671970-4379d31c-88eb-11e7-9f27-208d6faa1b2e.png)

Therefore I assumed the "row head" to be present:
![grafik](https://user-images.githubusercontent.com/6699539/29672018-64dbc04c-88eb-11e7-9f5a-3789be337dad.png)

But it doesn't do. After 10 minutes and workarounds editing the plain XML I've posted to the Camunda forum and was told that you can actually open a context menu in the cells.
While "my problem" is solved by this knowledge it is still bad to have two different behaviors (support context for "column head" but not for "row head") and may confuse other people, too (I've asked 2 people (beginners with the camunda modeler) before if they know a way to do this without the XML - and they only told me "nope" this seems to be not possible - bad software - which it obviously isn't). I therefore tried to fix it and provide a PR...

Checking in the code I've found https://github.com/bpmn-io/dmn-js/blob/7998150a746d754273730ece02358d69f3d8106e/lib/table/features/context-menu/ContextMenu.js to contain a comment ` // Do not open context menu on table footer` but directly below actually handling the utilityColumn, too (which I believe to be the "row head" which shows the number).

Please reopen this issue and either:

a. completely remove the context menu in the "headers": 
    * remove it from the "column headers", too
    * correct the comment to include the "headers", too

or preferably:

b. add it back for the "row headers" (ensuring only the "Rule" part is in)

Thank you.

**Comment by GitMensch** [comment]
@philippfromme Can you please reopen this ticket (or create a new one)?

**Comment by GitMensch** [comment]
@SebastianStamm Was your assignment to @philippfromme thought for reviewing this issue?

**Comment by SebastianStamm** [comment]
@GitMensch Sorry for not getting back to you earlier! Yes, @philippfromme is currently maintaining the repository. We are in the process of making some major refactorings/rewritings so it's hard to look at this issue in isolation. However, we keep this issue in mind when working on the new version. Thank you for pointing it out!

**Comment by GitMensch** [comment]
@SebastianStamm OK - then please reopen the issue, otherwise "it is closed, nothing to do here"

**Comment by GitMensch** [comment]
@SebastianStamm @philippfromme Can I request reopening this issue? Wile @SebastianStamm  said this should be investigated the issue is still closed...
