### ISSUE TITLE
Enable/Disable/Hide modules in DecisionTable

### ISSUE THREAD

**Issue by lampropoi** [bpmn-io/dmn-js#633]
__Is your feature request related to a problem? Please describe.__

I have different users and based on their roles, they should have different permissions on the Decision Table e.g., some users should only be allowed to add new rules but must not be allowed to add new inputs/outputs, others will be allowed to edit everything apart from the hitPolicyModule, others can edit everything, etc

__Describe the solution you'd like__

A possible solution would be when we initialise the DMN Modeler, to pass down a config object that controls the visibility of the Decision Table modules, e.g., lets say we pass the below config file:

```
 config = {
 addRuleModule: false,
 hitPolicyEditorModule: false
}
```
the app should render the DecisionTable with:

- the plus button (+) to add a new rule not displayed / rendered at all
- hitPolicy should  be a non-editable field

Would you be interested into an enhancement like the above and if yes, I can possibly help out :)

**Comment by pinussilvestrus** [comment]
Thanks for reporting! What would be the difference/benefit to have such a config instead of simply disabling modules via `additionalModules`?

```js
const dmnJS = new DmnJS({
  container: document.getElementById('container'),
  // ...
  decisionTable: {
    // ...
    additionalModules: [
      {
        addRule: ['value', null]
      }
    ]
  }
});
```

Source: https://codesandbox.io/s/dmn-js-remove-one-module-6x60f

**Comment by lampropoi** [comment]
I love the above solution :)

Although try to extend it to more modules and seems that some of the work while others not as expected e.g., is it possible to disable the + button so the user cannot add inputs/outputs,  hitPolicyEditorModule seems to always been enabled if we follow the above pattern, etc

What kind of pattern we can use to enable / disable any functionality we want?

Thanks a lot for the quick reply :)

**Comment by lampropoi** [comment]
@pinussilvestrus thanks a lot for the reply! It works as a treat :tada: :tada: :tada:

**Comment by enote-kane** [comment]
@lampropoi Sorry to hijack this one, but how did you manage to make the hit policy read-only?

With this, I've just managed to disable it completely:
```javascript
new DmnModeler({
  container: "#canvas",
  decisionTable: {
    additionalModules: [
      {
        viewDrd: ["value", null],
        hitPolicyProvider: ["value", null],
      },
    ],
  },
});
```

@pinussilvestrus In general, is there any documentation about which values for the module name keys are acceptable?
