### ISSUE TITLE
Different actions for different tables/expressions inside the same digram

### ISSUE THREAD

**Issue by lampropoi** [bpmn-io/dmn-js#655]
__Is your feature request related to a problem? Please describe.__

Let 's say I have a DRD that includes two decision tables, A and B.
I would like to load the modeler, so that in decision table A the user can do different actions from decision table B.

__Describe the solution you'd like__

ATM, when we initialise the modeler, we can include additional modules that affect the whole diagram. That means, if I disable the add-rule property, for all the decisions tables inside that diagram, the user is not able to add a rule. Ideally, on load, we could pass our own config file per each decision table / expression.

__Describe alternatives you've considered__
We could possibly initialise the modeler with a default config and before clicking on a table / expression, a way to override the default configuration for the clickable item should be given

**Comment by nikku** [comment]
Thanks for opening this issue.

Could you elaborate on your use-case? Why would you want a user to have different behaviors per decision table?

**Comment by lampropoi** [comment]
Different users would have different permissions inside the same digram :) So, ideally before rendering every table, we would check the permissions of the user and load the modules needed for that user :)

**Comment by barmac** [comment]
This sounds more like a custom extension idea, but we are not going to include that in the core library.
