### ISSUE TITLE
Update Examples step post release fails

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#658]
__Describe the Bug__

This was observed with the 11.0.2 release.
The post release step to `update examples` fails.

__Steps to Reproduce__

See https://github.com/bpmn-io/dmn-js/runs/3536886091

__Expected Behavior__

The task should succeed. Otherwise it has to be done manually.

**Comment by nikku** [comment]
Need to pull in recent CI changes to fix this, cf. https://github.com/bpmn-io/form-js/pull/174.
