### ISSUE TITLE
Simple Mode does not show [expression] for numbers in Viewer

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#70]
Reproduce:
- have a dmn xml file that contains an expression for a number cell
- open the file in Viewer mode (not the modeler)
- ensure that simple mode is activated
- The plain text expression is shown in the 
  cell
- Expected: Like in the Modeler, [expression] is shown

**Comment by nikku** [comment]
Simplemode is gone in `dmn-js@2`.
