### ISSUE TITLE
Unable to import Java classes: Illegal char<:> at index 4

### ISSUE THREAD

**Issue by MariuszCwikla** [bpmn-io/dmn-js#703]
__Describe the Bug__

I am unable to import java classes.  When typing the name of the class in the search box, no class appear.
In Developer tools I see following error:

```
dmn-loader.js:2 Error: Illegal char <:> at index 4: file://D:\src\drools\kogito-examples\kogito-quarkus-examples\dmn-quarkus-example\src\main\java\com\mc\Activator.java
    at e.callback (DmnEditorEnvelopeApp.js:2:517048)
    at e.receive (DmnEditorEnvelopeApp.js:2:518804)
    at Object.receive (DmnEditorEnvelopeApp.js:2:514121)
    at e.receive (DmnEditorEnvelopeApp.js:2:521333)
    at eventListener.eventListener (DmnEditorEnvelopeApp.js:2:520493)
```

I was following this blog post entry https://blog.kie.org/2022/05/dmn-types-from-java-classes.html. I tried creating my own project and also cloned examples repository. Same issue on both.

__Steps to Reproduce__

1. open https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/dmn-quarkus-example in VS Code
2. create Activator class:

```
package com.mc;

import org.kie.api.project.KieActivator;

@KieActivator
public class Activator {
    
}
```

3. create java bean:

```
package com.mc;

public class Person {
    String firstName;
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
}
```

4. Open `Traffic Violation.dmn` and try to search the `Person` class
5. In Developer tools `Error: Illegal char <:> at index 4: ` error appears.

__Expected Behavior__

Plugin should be able to fetch my model classes.

__Environment__

- OS: Windows
- Visual Studio Code version: 1.68.1
- DMN Editor plugin: 0.20.0
- Language Support for Java(TM) by Red Hat v1.8.0

Blog post entry also talks about Kogito (1.22.0+), but I don't have it. Is it really needed for this feature?

Sorry if reporting issue in wrong repo...

**Comment by barmac** [comment]
Hi,

Indeed, this is not a proper repo to report this issue. This repo is about dmn-js which is one of core libraries of [bpmn.io](https://bpmn.io/) project. Kogito and related projects may also implement DMN, but they are not developed within our project. I guess you could look for the right repo within [the kiegroup organisation](https://github.com/kiegroup).

Best

Maciej
