### ISSUE TITLE
In simple mode, boolean navigation with enter is broken

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#71]
- be in simple mode
- navigate to boolean body cell, change type with keyboard (using space to open dropdown, arrow keys to select, enter to confirm)
- press enter to goto cell below
- press space to open dropdown

Expected:
- dropdown opened for cell below

Observed:
- dropdown opened for cell above

**Comment by nikku** [comment]
Not relevant anymore (simple mode is gone with `dmn-js@v2.0.0`).
