### ISSUE TITLE
Decision table input/output label is being cut off

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#719]
__Describe the Bug__

When entering a longer decision table name the name is being cut of despite space being available vertically. Trying to hover over the name doesn't show it to me either, but shows "Input Label" instead: 

![capture iZ8ysZ_optimized](https://user-images.githubusercontent.com/58601/201037946-4a79e91c-ef49-4bd6-b232-fe6546661425.gif)

__Steps to Reproduce__

1. open [test diagram](https://github.com/bpmn-io/dmn-js/files/9978786/long-label.dmn.txt)
2. see that label is cut off and cannot be retrieved without double clicking the header

Can be reproduced on https://demo.bpmn.io/dmn (just decrease secreen size)

__Expected Behavior__

* [ ] We show the label on a best effort basis, i.e. multi-line if needed. This is a practice that other tools follow, too (cf. Excel / Google sheets)

__Environment__

Please complete the following information:

 - Browser: Any
 - OS: Any
 - Library version: 13.0.0

**Comment by nikku** [comment]
@marstamm I presume this is closed via https://github.com/bpmn-io/dmn-js/pull/736?

**Comment by marstamm** [comment]
Yes, closed via #736 . Missed to put the `closes` tag in the commit

**Comment by GeethaParthasarathy** [comment]
This issue is reproducible for the output label and hence needs to be reopened.

<img width="960" alt="fe14a3a0d96d8c579ae06644c6986395" src="https://user-images.githubusercontent.com/85225325/217863844-cd4af352-fcd1-4882-a9de-33fc9f9b0696.png">

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/737.
