### ISSUE TITLE
Can you set the default color like bpmn js (for example, defaultFillColor and defaultStrokeColor in bpmn js)

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/dmn-js#760]
__Is your feature request related to a problem? Please describe.__

1. Can you set the default color like bpmn js (for example, defaultFillColor and defaultStrokeColor in bpmn js)
2. This is especially useful in certain environments, such as dark mode

**Comment by nikku** [comment]
@zxuanhong We'd need to implement this in a proper way across all DMN editors, or are you interested in a DRD only solution? 

DRD is fairly straight forward; just copy what we got in the BPMN rendering department. The other editors are probably easier to override via CSS?

**Comment by nikku** [comment]
@zxuanhong It looks like the `drd` editor already supports this. Please check [this comment](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-drd/src/draw/DrdRenderer.js#L45). If there is anything else you need, please raise your voice.
