### ISSUE TITLE
Cannot change cell expression language

### ISSUE THREAD

**Issue by Egoplayer** [bpmn-io/dmn-js#766]
__Describe the Bug__

With this version of the DMN modeler, you are no longer able to change the expression language used by a particular cell. The entry in the right-click menu vanished.

![image](https://github.com/bpmn-io/dmn-js/assets/25846978/2a5d8328-9eff-4262-86dc-74a071a24c84)

compared to:

![image](https://github.com/bpmn-io/dmn-js/assets/25846978/a347fbb2-8bf4-486a-9524-43aebf187d60)

__Steps to Reproduce__

1. Open a new DMN
2. Create a new rule
3. Right-click in an empty cell.

There should be a menu entry "Change Cell Expression Language" but this seems to be no longer available

__Expected Behavior__

As in earlier versions there should be a menu entry "Change Cell Expression Language" followed by a drop down menu to select the expression language I want to use for this cell

__Environment__

Please complete the following information:

 - Browser: [Chrome 107]
 - OS: [Windows 7]
 - Library version: [14.1.5]

**Comment by nikku** [comment]
@Egoplayer This is intentional and I'd ask you to check the CHANGELOG for potential breaking changes across library versions we release.

Nowadays we align closer to the DMN spec which proposes FEEL as the expression language of choice for DMN.

**Comment by Egoplayer** [comment]
Thanks for letting me know. I searched for a changelog to check this but I didn't find it. Can you provide a link? your link above is only targeting the repository without a changelog file

**Comment by nikku** [comment]
[This](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js/CHANGELOG.md#1200) is the relevant changelog entry.
