### ISSUE TITLE
The translation did not take effect.

### ISSUE THREAD

**Issue by HaiYuanQi** [bpmn-io/dmn-js#767]
__Describe the Bug__
The translation did not take effect.
The 'alert' in the following code was not executed

__Steps to Reproduce__

`import DmnModeler from "dmn-js/lib/Modeler"`

`const dmnModeler = new DmnModeler({`
    
    additionalModules: [
      {
        translate: [ 'value', (template, replacements) => {
        alert(1) // The action was not executed.
          return 'Test'
        }]
      }
    ],
    table: {
      additionalModules: [
        {
          translate: [ 'value', (template, replacements) => {
          alert(1) // The action was not executed.
            return 'Test'
          }]
        }
      ]
    },
    container: dom.value,
    keyboard: {
      bindTo: window
    },
    disableDrdInteraction: true,`
 ` });`
 `dmnModeler.importXML(xml);`

__Environment__

 - Browser: [Chrome 114]
 - OS: [Windows 10]
 - Library version: [14.1.5]

**Comment by philippfromme** [comment]
You need to use the ID of the respective editor to pass additional modules to it: https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-shared/src/base/Manager.js#L673. Try `decisionTable` instead of `table`. Pretty sure this is not a bug.

**Comment by HaiYuanQi** [comment]
Thank you very much, the issue has been resolved.
