### ISSUE TITLE
Literal Expression view should not leave available space empty

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js#789]
__Is your feature request related to a problem? Please describe.__

I'm always frustrated when I have to scroll the literal expression view even though there is so much space below.

![image](https://github.com/bpmn-io/dmn-js/assets/28307541/60e2b07c-3af8-4b32-8596-d3d253564c7e)

__Describe the solution you'd like__

It should either take all the space remaining or grow with the content:

![image](https://github.com/bpmn-io/dmn-js/assets/28307541/caf2809f-a1a9-485f-89f5-985f54929ff9)

__Describe alternatives you've considered__

One of two above.

__Additional context__

Reported by @falko

**Comment by falko** [comment]
Another option would be to offer a manual resize of the text area but since the space below is not used for anything else, the most reasonable would be to simply use that space for the only element of variable size content.

**Comment by nikku** [comment]
I'd advocate for reasonable default size + auto-resizing (growing with contents). This is something we have in place in the properties panel* code editors, and it works well.
