### ISSUE TITLE
Improve parsing for numbers in simple mode

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#81]
Currently, we require a whitespace between the operator and the value for numbers in simple mode. We should make the regexp more flexible to improve usability.

![image001 1](https://cloud.githubusercontent.com/assets/8982136/18441421/4efd4064-790d-11e6-99fe-4f439fe1d95a.png)
![image002](https://cloud.githubusercontent.com/assets/8982136/18441423/503bcbf8-790d-11e6-8e28-70f09e36e792.png)

**Comment by vkatushenok** [comment]
@SebastianStamm If you enter on advanced mode something like '>1000' it does show up in simple mode in the cell. However, when you click on it, the expression is not correctly parsed and is removed on closing popup.
