### ISSUE TITLE
Border invisible in case of Firefox browser

### ISSUE THREAD

**Issue by romero83** [bpmn-io/dmn-js#82]
Hi,

dmn-js version: 0.6.0
There are no "header cell" borders in case of Firefox browser. See screenshot:
![no_border](https://cloud.githubusercontent.com/assets/9417960/18464509/d10b2704-7991-11e6-95d9-2ff79498a653.PNG)

**Comment by romero83** [comment]
Just added the following CSS line fixed the issue:

```
.dmn-table td, .dmn-table th {
    background-clip: padding-box;
}
```

**Comment by SebastianStamm** [comment]
Hi,

thanks for reporting and cool that you figured it out 👍 Do you want to send a pull request so we can get it into the codebase?

**Comment by romero83** [comment]
I leave it up to you. I am not exactly familiar with it to how to do that.

**Comment by SebastianStamm** [comment]
Alright, I will add it to our backlog

**Comment by menski** [comment]
The same problem exists in Internet Explorer 11
