### ISSUE TITLE
FEEL editor does not properly handle multi-line cells

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#838]
### Describe the Bug

When I have a [decision table with multiple lines in a cell](https://github.com/bpmn-io/dmn-js/files/14726042/simple.dmn.txt), then the FEEL editor looks super odd: 

![capture z0PTeB_optimized](https://github.com/bpmn-io/dmn-js/assets/58601/8120beb3-0573-4b13-95a4-0e63dc2fad6f)

### Steps to Reproduce

1. open [test diagram](https://github.com/bpmn-io/dmn-js/files/14726042/simple.dmn.txt)
2. see above broken behavior

### Expected Behavior

Editor fits to cell, and overflows if space is not enough. We employ automatic line wrapping (to fit contents) to mimic textarea behavior.

### Environment

Please complete the following information:

 - Browser: Chrome
 - OS: Linux
 - Library version: v16.0.1

**Comment by barmac** [comment]
I can reproduce this.

**Comment by nikku** [comment]
@barmac Did we by any chance address this issue? I cannot reproduce anymore integrating the latest dmn-js version into our demo:

![capture W8pbAC_optimized](https://github.com/bpmn-io/dmn-js/assets/58601/ab58e18e-a09a-4adb-8f67-15d6e9fe7ebf)

**Comment by nikku** [comment]
Never mind, this is still an issue for overflowing content: 

![image](https://github.com/bpmn-io/dmn-js/assets/58601/239350de-bd89-4a22-ae51-9e9babdb8a66)

**Comment by nikku** [comment]
Should be an easy fix (adapt properties panel behavior), cf. https://github.com/bpmn-io/properties-panel/blob/1b2cbec8e55bfb470695bde2a302e60110a65261/src/components/entries/FEEL/FeelEditor.js#L103.

**Comment by barmac** [comment]
Thanks for the insight. This will be useful for a person who fixes this.

**Comment by nikku** [comment]
I'll have a look if it is this easy :heavy_check_mark:
