### ISSUE TITLE
DMN Overlay buttons must have discernible text

### ISSUE THREAD

**Issue by vpellegrino** [bpmn-io/dmn-js#842]
### Describe the Bug

The buttons used for navigating from the DRD to the Decision Table or the Literal Expression definitions must have text that describes their purpose.

Axe recommendation:
To solve this problem, you need to fix at least (1) of the following:
- Element does not have inner text that is visible to screen readers
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has no title attribute
- Element's default semantics were not overridden with role="none" or role="presentation"
 
![image](https://github.com/bpmn-io/dmn-js/assets/22591802/5e3cca45-5b90-432c-a47f-0926c079f087)

My suggestion is to just add a **title** attribute to the buttons, with a small explanation of the button purpose (e.g. `title="Navigate to the Decision Table definition"`).

### Steps to Reproduce

1. Open the DMN editor (for example, on the Web Modeler)
2. Create a new Decision Table/Literal Expression
3. Execute the page scan, by using the ["axe DevTools" extension](https://www.deque.com/axe/devtools/)

### Expected Behavior

The axe scan reports no accessibility issue related to the overlay buttons.

### Environment

Please complete the following information:

 - Browser: Chrome
 - OS: MacOS
 - Library version: Library version: current one (reproducible on https://demo.bpmn.io/dmn/new)

**Comment by vpellegrino** [comment]
@nikku, feel free to include this one in https://github.com/bpmn-io/internal-docs/issues/909

**Comment by vpellegrino** [comment]
@barmac was this issue fixed too with [this bump](https://github.com/camunda/web-modeler/pull/8881)?

**Comment by barmac** [comment]
Correct, this is supposed to be fixed in v16.1.0

**Comment by nikku** [comment]
Fixed, cf. https://github.com/bpmn-io/dmn-js/issues/842#issuecomment-2039516080.
