### ISSUE TITLE
Localize labels (I18N)

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/dmn-js#88]
Support localization for label. We should closely match the [bpmn-js implementation](https://github.com/bpmn-io/bpmn-js/issues/491).

__Tasks__

* [ ] Labels are piped through a `translate` helper to provide a simple localization stub

**Comment by rbatllet** [comment]
This feature will be nice to have!

**Comment by nikku** [comment]
Related to https://github.com/bpmn-io/dmn-js/issues/230.

**Comment by chfarias** [comment]
Some news about this feature? Thanks for the great work!

**Comment by pinussilvestrus** [comment]
Unfortunately, it's not on our early Roadmap atm. But we're thankful for any kind of external contribution here 👍🏻
