### ISSUE TITLE
an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by deble6** [bpmn-io/dmn-js#901]
The following error message is displayed when the project is running after download: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by barmac** [comment]
Is this a feature request or a bug report? Please update the issue with one of the issue templates: https://github.com/bpmn-io/dmn-js/issues/new/choose

**Comment by deble6** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我是江，你的邮箱我已收到，不用回复，谢谢。

**Comment by philippfromme** [comment]
@deble6 Please provide more information, otherwise we cannot act on this issue and will be forced to close it.
