### ISSUE TITLE
Port implicit keyboard binding over to decision editors

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#920]
### Is your feature request related to a problem? Please describe.

With https://github.com/bpmn-io/diagram-js/pull/662 we made sure that keyboard binding works with browser focus, implicitly, and well integrated into the users UX flow. This is not fully integrated in our DMN editors yet, with explicit [bind stubs remaining](https://github.com/search?q=repo%3Abpmn-io%2Fdmn-js%20bindTo&type=code).

### Describe the solution you'd like

* We want to ensure that all editors work in the same way, and that explicit binding is no longer necessary.

### Describe alternatives you've considered

None.

### Additional context

Child of https://github.com/bpmn-io/internal-docs/issues/1081

**Comment by nikku** [comment]
(We could also consider it a bug that this is not properly integrated (yet), hence any follow-up improvement in the same style is not a user land break anymore).

**Comment by barmac** [comment]
Since the change was already announced, indeed this looks like an incomplete implementation hence bug.

**Comment by jarekdanielak** [comment]
Let's consider it a bug then.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/dmn-js/pull/921

**Comment by jarekdanielak** [comment]
I'm closing this issue. We added the new configuration, so the _bug_ is fixed.

I created a follow up issue to bring more UX improvements to DMN editors: https://github.com/bpmn-io/dmn-js/issues/926
