### ISSUE TITLE
Question: Best way to set a decision Id ?

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#93]
I don't know if it's possible to set a decision Id better than doing:

```
        const modeler = new DmnModeler({
          container,
          minColWidth: 200,
          tableName: ''
        });
       
       modeler.definitions.decision[0].id = 'myNewId';
```

Is there any way to do the same but through the api?

Note: I need to do this to avoid having the id value = 'decision' instead of id= 'decision_[random_values]'

**Comment by SebastianStamm** [comment]
The proper way to do that would be `modeler.get('tableName').setId('myNewId');` ([Implementation](https://github.com/bpmn-io/dmn-js/blob/master/lib/features/table-name/TableName.js#L60-L66))

Does that work for you?

**Comment by rbatllet** [comment]
Thank you!. It works.

**Comment by rbatllet** [comment]
Suggestion: A generated Id instead of "decision" for a table Id would be nice.
